<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TsDeweySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('ts_deweys')->insert(['id' =>'001', 'nombre' => 'Conocimiento', 'ss_deweys_id' => '000']);
        DB::table('ts_deweys')->insert(['id' =>'002', 'nombre' => 'El libro', 'ss_deweys_id' => '000']);
        DB::table('ts_deweys')->insert(['id' =>'003', 'nombre' => 'Sistemas', 'ss_deweys_id' => '000']);
        DB::table('ts_deweys')->insert(['id' =>'004', 'nombre' => 'Procesamiento de datos Ciencia de los computadores', 'ss_deweys_id' => '000']);
        DB::table('ts_deweys')->insert(['id' =>'005', 'nombre' => 'Programación, programas, datos de computación', 'ss_deweys_id' => '000']);
        DB::table('ts_deweys')->insert(['id' =>'006', 'nombre' => 'Métodos especiales de computación', 'ss_deweys_id' => '000']);
        DB::table('ts_deweys')->insert(['id' =>'011', 'nombre' => 'Bibliografías', 'ss_deweys_id' => '010']);
        DB::table('ts_deweys')->insert(['id' =>'012', 'nombre' => 'De individuos', 'ss_deweys_id' => '010']);
        DB::table('ts_deweys')->insert(['id' =>'013', 'nombre' => 'De obras por clases específicas de autores', 'ss_deweys_id' => '010']);
        DB::table('ts_deweys')->insert(['id' =>'014', 'nombre' => 'De obras anónimas y seudónimas', 'ss_deweys_id' => '010']);
        DB::table('ts_deweys')->insert(['id' =>'015', 'nombre' => 'De obras de lugares específicos', 'ss_deweys_id' => '010']);
        DB::table('ts_deweys')->insert(['id' =>'016', 'nombre' => 'De obras sobre temas específicos', 'ss_deweys_id' => '010']);
        DB::table('ts_deweys')->insert(['id' =>'017', 'nombre' => 'Catálogos generales por materia', 'ss_deweys_id' => '010']);
        DB::table('ts_deweys')->insert(['id' =>'018', 'nombre' => 'Catálogos ordenados por autor, fecha, etc.', 'ss_deweys_id' => '010']);
        DB::table('ts_deweys')->insert(['id' =>'019', 'nombre' => 'Catálogos diccionario', 'ss_deweys_id' => '010']);
        DB::table('ts_deweys')->insert(['id' =>'021', 'nombre' => 'Relaciones bibliotecarias', 'ss_deweys_id' => '020']);
        DB::table('ts_deweys')->insert(['id' =>'022', 'nombre' => 'Administración de la planta física', 'ss_deweys_id' => '020']);
        DB::table('ts_deweys')->insert(['id' =>'023', 'nombre' => 'Administración de personal', 'ss_deweys_id' => '020']);
        DB::table('ts_deweys')->insert(['id' =>'025', 'nombre' => 'Operaciones bibliotecarias', 'ss_deweys_id' => '020']);
        DB::table('ts_deweys')->insert(['id' =>'026', 'nombre' => 'Bibliotecas para temas específicos', 'ss_deweys_id' => '020']);
        DB::table('ts_deweys')->insert(['id' =>'027', 'nombre' => 'Bibliotecas generales', 'ss_deweys_id' => '020']);
        DB::table('ts_deweys')->insert(['id' =>'028', 'nombre' => 'Lectura, uso de otros medios de información', 'ss_deweys_id' => '020']);
        DB::table('ts_deweys')->insert(['id' =>'031', 'nombre' => 'Norteamericanas', 'ss_deweys_id' => '030']);
        DB::table('ts_deweys')->insert(['id' =>'032', 'nombre' => 'En inglés', 'ss_deweys_id' => '030']);
        DB::table('ts_deweys')->insert(['id' =>'033', 'nombre' => 'En otras lenguas germánicas', 'ss_deweys_id' => '030']);
        DB::table('ts_deweys')->insert(['id' =>'034', 'nombre' => 'En francés, provenzal, catalán', 'ss_deweys_id' => '030']);
        DB::table('ts_deweys')->insert(['id' =>'035', 'nombre' => 'En italiano, rumano, retorromano', 'ss_deweys_id' => '030']);
        DB::table('ts_deweys')->insert(['id' =>'036', 'nombre' => 'En español, y portugués', 'ss_deweys_id' => '030']);
        DB::table('ts_deweys')->insert(['id' =>'037', 'nombre' => 'En lenguas eslavas', 'ss_deweys_id' => '030']);
        DB::table('ts_deweys')->insert(['id' =>'038', 'nombre' => 'En lenguas escandinavas', 'ss_deweys_id' => '030']);
        DB::table('ts_deweys')->insert(['id' =>'039', 'nombre' => 'En otras lenguas', 'ss_deweys_id' => '030']);
        DB::table('ts_deweys')->insert(['id' =>'051', 'nombre' => 'Norteamericanas', 'ss_deweys_id' => '050']);
        DB::table('ts_deweys')->insert(['id' =>'052', 'nombre' => 'En inglés', 'ss_deweys_id' => '050']);
        DB::table('ts_deweys')->insert(['id' =>'053', 'nombre' => 'En otras lenguas germánicas', 'ss_deweys_id' => '050']);
        DB::table('ts_deweys')->insert(['id' =>'054', 'nombre' => 'En francés, provenzal, catalán', 'ss_deweys_id' => '050']);
        DB::table('ts_deweys')->insert(['id' =>'055', 'nombre' => 'En italiano, rumano, retorromano', 'ss_deweys_id' => '050']);
        DB::table('ts_deweys')->insert(['id' =>'056', 'nombre' => 'En español y portugués', 'ss_deweys_id' => '050']);
        DB::table('ts_deweys')->insert(['id' =>'057', 'nombre' => 'En lenguas eslavas', 'ss_deweys_id' => '050']);
        DB::table('ts_deweys')->insert(['id' =>'058', 'nombre' => 'En lenguas escandinavas', 'ss_deweys_id' => '050']);
        DB::table('ts_deweys')->insert(['id' =>'059', 'nombre' => 'En otras lenguas', 'ss_deweys_id' => '050']);
        DB::table('ts_deweys')->insert(['id' =>'061', 'nombre' => 'En América del Norte', 'ss_deweys_id' => '060']);
        DB::table('ts_deweys')->insert(['id' =>'062', 'nombre' => 'En las Islas Británicas. En Inglaterra', 'ss_deweys_id' => '060']);
        DB::table('ts_deweys')->insert(['id' =>'063', 'nombre' => 'En Europa central. En Alemania', 'ss_deweys_id' => '060']);
        DB::table('ts_deweys')->insert(['id' =>'064', 'nombre' => 'En Francia y Mónaco', 'ss_deweys_id' => '060']);
        DB::table('ts_deweys')->insert(['id' =>'065', 'nombre' => 'En Italia y territorios adyacentes', 'ss_deweys_id' => '060']);
        DB::table('ts_deweys')->insert(['id' =>'066', 'nombre' => 'En la Península Ibérica y islas adyacentes', 'ss_deweys_id' => '060']);
        DB::table('ts_deweys')->insert(['id' =>'067', 'nombre' => 'En Europa oriental Rusia', 'ss_deweys_id' => '060']);
        DB::table('ts_deweys')->insert(['id' =>'068', 'nombre' => 'En otras áreas', 'ss_deweys_id' => '060']);
        DB::table('ts_deweys')->insert(['id' =>'069', 'nombre' => 'Museología (Ciencia de los museos)', 'ss_deweys_id' => '060']);
        DB::table('ts_deweys')->insert(['id' =>'071', 'nombre' => 'En América del Norte', 'ss_deweys_id' => '070']);
        DB::table('ts_deweys')->insert(['id' =>'072', 'nombre' => 'En las Islas Británicas. En Inglaterra', 'ss_deweys_id' => '070']);
        DB::table('ts_deweys')->insert(['id' =>'073', 'nombre' => 'En Europa central. En Alemania', 'ss_deweys_id' => '070']);
        DB::table('ts_deweys')->insert(['id' =>'074', 'nombre' => 'En Francia y Mónaco', 'ss_deweys_id' => '070']);
        DB::table('ts_deweys')->insert(['id' =>'075', 'nombre' => 'En Asia y territorios adyacentes', 'ss_deweys_id' => '070']);
        DB::table('ts_deweys')->insert(['id' =>'076', 'nombre' => 'En la Península Ibérica y islas adyacentes', 'ss_deweys_id' => '070']);
        DB::table('ts_deweys')->insert(['id' =>'077', 'nombre' => 'En Europa oriental. En Rusia', 'ss_deweys_id' => '070']);
        DB::table('ts_deweys')->insert(['id' =>'078', 'nombre' => 'En Escandinavia', 'ss_deweys_id' => '070']);
        DB::table('ts_deweys')->insert(['id' =>'079', 'nombre' => 'En otras áreas geográficas', 'ss_deweys_id' => '070']);
        DB::table('ts_deweys')->insert(['id' =>'081', 'nombre' => 'Norteamericanas', 'ss_deweys_id' => '080']);
        DB::table('ts_deweys')->insert(['id' =>'082', 'nombre' => 'En inglés', 'ss_deweys_id' => '080']);
        DB::table('ts_deweys')->insert(['id' =>'083', 'nombre' => 'En otras lenguas germánicas', 'ss_deweys_id' => '080']);
        DB::table('ts_deweys')->insert(['id' =>'084', 'nombre' => 'En francés, provenzal, catalán', 'ss_deweys_id' => '080']);
        DB::table('ts_deweys')->insert(['id' =>'085', 'nombre' => 'En italiano, rumano, retorromano', 'ss_deweys_id' => '080']);
        DB::table('ts_deweys')->insert(['id' =>'086', 'nombre' => 'En español y portugués', 'ss_deweys_id' => '080']);
        DB::table('ts_deweys')->insert(['id' =>'087', 'nombre' => 'En lenguas eslavas', 'ss_deweys_id' => '080']);
        DB::table('ts_deweys')->insert(['id' =>'088', 'nombre' => 'En lenguas escandinavas', 'ss_deweys_id' => '080']);
        DB::table('ts_deweys')->insert(['id' =>'089', 'nombre' => 'En otras lenguas', 'ss_deweys_id' => '080']);
        DB::table('ts_deweys')->insert(['id' =>'091', 'nombre' => 'Manuscritos', 'ss_deweys_id' => '090']);
        DB::table('ts_deweys')->insert(['id' =>'092', 'nombre' => 'Libros xilográficos', 'ss_deweys_id' => '090']);
        DB::table('ts_deweys')->insert(['id' =>'093', 'nombre' => 'Incunables', 'ss_deweys_id' => '090']);
        DB::table('ts_deweys')->insert(['id' =>'094', 'nombre' => 'Libros impresos', 'ss_deweys_id' => '090']);
        DB::table('ts_deweys')->insert(['id' =>'095', 'nombre' => 'Libros notables por su encuadernación', 'ss_deweys_id' => '090']);
        DB::table('ts_deweys')->insert(['id' =>'096', 'nombre' => 'Libros notables por las ilustraciones', 'ss_deweys_id' => '090']);
        DB::table('ts_deweys')->insert(['id' =>'097', 'nombre' => 'Libros notables por su propietario u origen', 'ss_deweys_id' => '090']);
        DB::table('ts_deweys')->insert(['id' =>'098', 'nombre' => 'Obras prohibidas, Falsificaciones, imposturas', 'ss_deweys_id' => '090']);
        DB::table('ts_deweys')->insert(['id' =>'099', 'nombre' => 'Libros notables por su formato', 'ss_deweys_id' => '090']);
        DB::table('ts_deweys')->insert(['id' =>'101', 'nombre' => 'Teoría de la filosofía', 'ss_deweys_id' => '100']);
        DB::table('ts_deweys')->insert(['id' =>'102', 'nombre' => 'Miscelánea de filosofía', 'ss_deweys_id' => '100']);
        DB::table('ts_deweys')->insert(['id' =>'103', 'nombre' => 'Diccionario de filosofía', 'ss_deweys_id' => '100']);
        DB::table('ts_deweys')->insert(['id' =>'105', 'nombre' => 'Publicaciones en serie de filosofía', 'ss_deweys_id' => '100']);
        DB::table('ts_deweys')->insert(['id' =>'106', 'nombre' => 'Organizaciones en filosofía', 'ss_deweys_id' => '100']);
        DB::table('ts_deweys')->insert(['id' =>'107', 'nombre' => 'Educación, investigación en filosofía', 'ss_deweys_id' => '100']);
        DB::table('ts_deweys')->insert(['id' =>'108', 'nombre' => 'Clases de personas en filosofía', 'ss_deweys_id' => '100']);
        DB::table('ts_deweys')->insert(['id' =>'109', 'nombre' => 'Tratamiento histórico de la filosofía', 'ss_deweys_id' => '100']);
        DB::table('ts_deweys')->insert(['id' =>'111', 'nombre' => 'Ontología', 'ss_deweys_id' => '110']);
        DB::table('ts_deweys')->insert(['id' =>'113', 'nombre' => 'Cosmología (Filosofía de la naturaleza)', 'ss_deweys_id' => '110']);
        DB::table('ts_deweys')->insert(['id' =>'114', 'nombre' => 'Espacio', 'ss_deweys_id' => '110']);
        DB::table('ts_deweys')->insert(['id' =>'115', 'nombre' => 'Tiempo', 'ss_deweys_id' => '110']);
        DB::table('ts_deweys')->insert(['id' =>'116', 'nombre' => 'Cambio', 'ss_deweys_id' => '110']);
        DB::table('ts_deweys')->insert(['id' =>'117', 'nombre' => 'Estructura', 'ss_deweys_id' => '110']);
        DB::table('ts_deweys')->insert(['id' =>'118', 'nombre' => 'Fuerza y Energía', 'ss_deweys_id' => '110']);
        DB::table('ts_deweys')->insert(['id' =>'119', 'nombre' => 'Números y cantidad', 'ss_deweys_id' => '110']);
        DB::table('ts_deweys')->insert(['id' =>'121', 'nombre' => 'Epistemología (Teoría del conocimiento)', 'ss_deweys_id' => '120']);
        DB::table('ts_deweys')->insert(['id' =>'122', 'nombre' => 'Causalidad', 'ss_deweys_id' => '120']);
        DB::table('ts_deweys')->insert(['id' =>'123', 'nombre' => 'Determinismo e indeterminismo', 'ss_deweys_id' => '120']);
        DB::table('ts_deweys')->insert(['id' =>'124', 'nombre' => 'Teleología', 'ss_deweys_id' => '120']);
        DB::table('ts_deweys')->insert(['id' =>'126', 'nombre' => 'El yo', 'ss_deweys_id' => '120']);
        DB::table('ts_deweys')->insert(['id' =>'127', 'nombre' => 'El inconsciente y el subconsciente', 'ss_deweys_id' => '120']);
        DB::table('ts_deweys')->insert(['id' =>'128', 'nombre' => 'Género humano', 'ss_deweys_id' => '120']);
        DB::table('ts_deweys')->insert(['id' =>'129', 'nombre' => 'Origen y destino del alma individual', 'ss_deweys_id' => '120']);
        DB::table('ts_deweys')->insert(['id' =>'131', 'nombre' => 'Métodos ocultos para lograr bienestar', 'ss_deweys_id' => '130']);
        DB::table('ts_deweys')->insert(['id' =>'133', 'nombre' => 'Parapsicología y ocultismo', 'ss_deweys_id' => '130']);
        DB::table('ts_deweys')->insert(['id' =>'135', 'nombre' => 'Sueños y misterios ', 'ss_deweys_id' => '130']);
        DB::table('ts_deweys')->insert(['id' =>'137', 'nombre' => 'Grafología adivinatoria', 'ss_deweys_id' => '130']);
        DB::table('ts_deweys')->insert(['id' =>'138', 'nombre' => 'Fisionomía', 'ss_deweys_id' => '130']);
        DB::table('ts_deweys')->insert(['id' =>'139', 'nombre' => 'Frenología ', 'ss_deweys_id' => '130']);
        DB::table('ts_deweys')->insert(['id' =>'141', 'nombre' => 'Idealismo y sistemas relacionados', 'ss_deweys_id' => '140']);
        DB::table('ts_deweys')->insert(['id' =>'142', 'nombre' => 'Filosofía critica', 'ss_deweys_id' => '140']);
        DB::table('ts_deweys')->insert(['id' =>'143', 'nombre' => 'Intuicionalismo y bergsonismo', 'ss_deweys_id' => '140']);
        DB::table('ts_deweys')->insert(['id' =>'144', 'nombre' => 'Humanismo y sistemas relacionados', 'ss_deweys_id' => '140']);
        DB::table('ts_deweys')->insert(['id' =>'145', 'nombre' => 'Sensacionalismo', 'ss_deweys_id' => '140']);
        DB::table('ts_deweys')->insert(['id' =>'146', 'nombre' => 'Naturalismo y sistemas relacionados', 'ss_deweys_id' => '140']);
        DB::table('ts_deweys')->insert(['id' =>'147', 'nombre' => 'Panteísmo y sistemas relacionados', 'ss_deweys_id' => '140']);
        DB::table('ts_deweys')->insert(['id' =>'148', 'nombre' => 'Liberalismo, eclecticismo, tradicionalismo', 'ss_deweys_id' => '140']);
        DB::table('ts_deweys')->insert(['id' =>'149', 'nombre' => 'Otros sistemas filosóficos', 'ss_deweys_id' => '140']);
        DB::table('ts_deweys')->insert(['id' =>'152', 'nombre' => 'Percepción, movimiento, emociones, impulsos', 'ss_deweys_id' => '150']);
        DB::table('ts_deweys')->insert(['id' =>'153', 'nombre' => 'Procesos mentales y inteligencia', 'ss_deweys_id' => '150']);
        DB::table('ts_deweys')->insert(['id' =>'154', 'nombre' => 'Subconsciente y estados alterados', 'ss_deweys_id' => '150']);
        DB::table('ts_deweys')->insert(['id' =>'155', 'nombre' => 'Psicología diferencial y del desarrollo', 'ss_deweys_id' => '150']);
        DB::table('ts_deweys')->insert(['id' =>'156', 'nombre' => 'Psicología comparada', 'ss_deweys_id' => '150']);
        DB::table('ts_deweys')->insert(['id' =>'158', 'nombre' => 'Psicología aplicada', 'ss_deweys_id' => '150']);
        DB::table('ts_deweys')->insert(['id' =>'161', 'nombre' => 'Inducción', 'ss_deweys_id' => '160']);
        DB::table('ts_deweys')->insert(['id' =>'162', 'nombre' => 'Deducción', 'ss_deweys_id' => '160']);
        DB::table('ts_deweys')->insert(['id' =>'165', 'nombre' => 'Falacias y fuentes de error', 'ss_deweys_id' => '160']);
        DB::table('ts_deweys')->insert(['id' =>'166', 'nombre' => 'Silogismos', 'ss_deweys_id' => '160']);
        DB::table('ts_deweys')->insert(['id' =>'167', 'nombre' => 'Hipótesis', 'ss_deweys_id' => '160']);
        DB::table('ts_deweys')->insert(['id' =>'168', 'nombre' => 'Argumento y persuasión', 'ss_deweys_id' => '160']);
        DB::table('ts_deweys')->insert(['id' =>'169', 'nombre' => 'Analogía', 'ss_deweys_id' => '160']);
        DB::table('ts_deweys')->insert(['id' =>'171', 'nombre' => 'Sistemas y doctrinas', 'ss_deweys_id' => '170']);
        DB::table('ts_deweys')->insert(['id' =>'172', 'nombre' => 'Ética política', 'ss_deweys_id' => '170']);
        DB::table('ts_deweys')->insert(['id' =>'173', 'nombre' => 'Ética de las relaciones familiares', 'ss_deweys_id' => '170']);
        DB::table('ts_deweys')->insert(['id' =>'174', 'nombre' => 'Ética económica y profesional', 'ss_deweys_id' => '170']);
        DB::table('ts_deweys')->insert(['id' =>'175', 'nombre' => 'Ética de la recreación y del tiempo libre', 'ss_deweys_id' => '170']);
        DB::table('ts_deweys')->insert(['id' =>'176', 'nombre' => 'Ética sexual y de la reproducción', 'ss_deweys_id' => '170']);
        DB::table('ts_deweys')->insert(['id' =>'177', 'nombre' => 'Ética de las relaciones sociales', 'ss_deweys_id' => '170']);
        DB::table('ts_deweys')->insert(['id' =>'178', 'nombre' => 'Ética del consumo', 'ss_deweys_id' => '170']);
        DB::table('ts_deweys')->insert(['id' =>'179', 'nombre' => 'Otras normas éticas', 'ss_deweys_id' => '170']);
        DB::table('ts_deweys')->insert(['id' =>'181', 'nombre' => 'Filosofía oriental', 'ss_deweys_id' => '180']);
        DB::table('ts_deweys')->insert(['id' =>'182', 'nombre' => 'Filosofías griegas, presocráticas', 'ss_deweys_id' => '180']);
        DB::table('ts_deweys')->insert(['id' =>'183', 'nombre' => 'Filosofías sofista y socrática', 'ss_deweys_id' => '180']);
        DB::table('ts_deweys')->insert(['id' =>'184', 'nombre' => 'Filosofía platónica', 'ss_deweys_id' => '180']);
        DB::table('ts_deweys')->insert(['id' =>'185', 'nombre' => 'Filosofía aristotélica', 'ss_deweys_id' => '180']);
        DB::table('ts_deweys')->insert(['id' =>'186', 'nombre' => 'Filosofía escéptica y neoplatónica', 'ss_deweys_id' => '180']);
        DB::table('ts_deweys')->insert(['id' =>'187', 'nombre' => 'Filosofía epicúrea', 'ss_deweys_id' => '180']);
        DB::table('ts_deweys')->insert(['id' =>'188', 'nombre' => 'Filosofía estoica', 'ss_deweys_id' => '180']);
        DB::table('ts_deweys')->insert(['id' =>'189', 'nombre' => 'Filosofía medieval occidental', 'ss_deweys_id' => '180']);
        DB::table('ts_deweys')->insert(['id' =>'191', 'nombre' => 'Estados Unidos y Canadá', 'ss_deweys_id' => '190']);
        DB::table('ts_deweys')->insert(['id' =>'192', 'nombre' => 'Islas Británicas', 'ss_deweys_id' => '190']);
        DB::table('ts_deweys')->insert(['id' =>'193', 'nombre' => 'Alemania y Austria', 'ss_deweys_id' => '190']);
        DB::table('ts_deweys')->insert(['id' =>'194', 'nombre' => 'Francia', 'ss_deweys_id' => '190']);
        DB::table('ts_deweys')->insert(['id' =>'195', 'nombre' => 'Italia', 'ss_deweys_id' => '190']);
        DB::table('ts_deweys')->insert(['id' =>'196', 'nombre' => 'España y Portugal', 'ss_deweys_id' => '190']);
        DB::table('ts_deweys')->insert(['id' =>'197', 'nombre' => 'Anterior Unión Soviética', 'ss_deweys_id' => '190']);
        DB::table('ts_deweys')->insert(['id' =>'198', 'nombre' => 'Escandinavia', 'ss_deweys_id' => '190']);
        DB::table('ts_deweys')->insert(['id' =>'199', 'nombre' => 'Otras áreas geográficas', 'ss_deweys_id' => '190']);
        DB::table('ts_deweys')->insert(['id' =>'201', 'nombre' => 'Filosofía del cristianismo', 'ss_deweys_id' => '200']);
        DB::table('ts_deweys')->insert(['id' =>'202', 'nombre' => 'Miscelánea del cristianismo', 'ss_deweys_id' => '200']);
        DB::table('ts_deweys')->insert(['id' =>'203', 'nombre' => 'Diccionarios del cristianismo', 'ss_deweys_id' => '200']);
        DB::table('ts_deweys')->insert(['id' =>'204', 'nombre' => 'Temas especiales', 'ss_deweys_id' => '200']);
        DB::table('ts_deweys')->insert(['id' =>'205', 'nombre' => 'Publicaciones en serie del cristianismo', 'ss_deweys_id' => '200']);
        DB::table('ts_deweys')->insert(['id' =>'206', 'nombre' => 'Organizaciones del cristianismo', 'ss_deweys_id' => '200']);
        DB::table('ts_deweys')->insert(['id' =>'207', 'nombre' => 'Educación, investigación en cristianismo', 'ss_deweys_id' => '200']);
        DB::table('ts_deweys')->insert(['id' =>'208', 'nombre' => 'Clases de personas en el cristianismo', 'ss_deweys_id' => '200']);
        DB::table('ts_deweys')->insert(['id' =>'209', 'nombre' => 'Historia y geografía del cristianismo', 'ss_deweys_id' => '200']);
        DB::table('ts_deweys')->insert(['id' =>'211', 'nombre' => 'Conceptos de Dios', 'ss_deweys_id' => '210']);
        DB::table('ts_deweys')->insert(['id' =>'212', 'nombre' => 'Existencia, atributos de Dios', 'ss_deweys_id' => '210']);
        DB::table('ts_deweys')->insert(['id' =>'213', 'nombre' => 'Creación', 'ss_deweys_id' => '210']);
        DB::table('ts_deweys')->insert(['id' =>'214', 'nombre' => 'Teodicea', 'ss_deweys_id' => '210']);
        DB::table('ts_deweys')->insert(['id' =>'215', 'nombre' => 'Ciencias y religión ', 'ss_deweys_id' => '210']);
        DB::table('ts_deweys')->insert(['id' =>'216', 'nombre' => 'El bien y el ma', 'ss_deweys_id' => '210']);
        DB::table('ts_deweys')->insert(['id' =>'218', 'nombre' => 'El Hombre', 'ss_deweys_id' => '210']);
        DB::table('ts_deweys')->insert(['id' =>'221', 'nombre' => 'Antiguo Testamento', 'ss_deweys_id' => '220']);
        DB::table('ts_deweys')->insert(['id' =>'222', 'nombre' => 'Libros históricos del Antiguo Testamento', 'ss_deweys_id' => '220']);
        DB::table('ts_deweys')->insert(['id' =>'223', 'nombre' => 'Libros poéticos del Antiguo Testamento', 'ss_deweys_id' => '220']);
        DB::table('ts_deweys')->insert(['id' =>'224', 'nombre' => 'Libros proféticos del Antiguo Testamento', 'ss_deweys_id' => '220']);
        DB::table('ts_deweys')->insert(['id' =>'225', 'nombre' => 'Nuevo Testamento', 'ss_deweys_id' => '220']);
        DB::table('ts_deweys')->insert(['id' =>'226', 'nombre' => 'Evangelios y Hechos de los Apóstoles', 'ss_deweys_id' => '220']);
        DB::table('ts_deweys')->insert(['id' =>'227', 'nombre' => 'Epístolas', 'ss_deweys_id' => '220']);
        DB::table('ts_deweys')->insert(['id' =>'228', 'nombre' => 'Revelación (Apocalipsis de Juan)', 'ss_deweys_id' => '220']);
        DB::table('ts_deweys')->insert(['id' =>'229', 'nombre' => 'Apócrifos y seudoepígrafes', 'ss_deweys_id' => '220']);
        DB::table('ts_deweys')->insert(['id' =>'231', 'nombre' => 'Dios', 'ss_deweys_id' => '230']);
        DB::table('ts_deweys')->insert(['id' =>'232', 'nombre' => 'Jesucristo y su familia', 'ss_deweys_id' => '230']);
        DB::table('ts_deweys')->insert(['id' =>'233', 'nombre' => 'El hombre', 'ss_deweys_id' => '230']);
        DB::table('ts_deweys')->insert(['id' =>'234', 'nombre' => 'Salvación (Soteriología) y gracia', 'ss_deweys_id' => '230']);
        DB::table('ts_deweys')->insert(['id' =>'235', 'nombre' => 'Seres espirituales', 'ss_deweys_id' => '230']);
        DB::table('ts_deweys')->insert(['id' =>'236', 'nombre' => 'Escatología', 'ss_deweys_id' => '230']);
        DB::table('ts_deweys')->insert(['id' =>'238', 'nombre' => 'Credos y catecismos', 'ss_deweys_id' => '230']);
        DB::table('ts_deweys')->insert(['id' =>'239', 'nombre' => 'Apologética y polémica', 'ss_deweys_id' => '230']);
        DB::table('ts_deweys')->insert(['id' =>'241', 'nombre' => 'Teología moral', 'ss_deweys_id' => '240']);
        DB::table('ts_deweys')->insert(['id' =>'242', 'nombre' => 'Literatura piadosa', 'ss_deweys_id' => '240']);
        DB::table('ts_deweys')->insert(['id' =>'243', 'nombre' => 'Escritos evangelizadores para individuos', 'ss_deweys_id' => '240']);
        DB::table('ts_deweys')->insert(['id' =>'245', 'nombre' => 'Textos de himnos', 'ss_deweys_id' => '240']);
        DB::table('ts_deweys')->insert(['id' =>'246', 'nombre' => 'Uso del arte en el cristianismo', 'ss_deweys_id' => '240']);
        DB::table('ts_deweys')->insert(['id' =>'247', 'nombre' => 'Mobiliario y artículos eclesiásticos', 'ss_deweys_id' => '240']);
        DB::table('ts_deweys')->insert(['id' =>'248', 'nombre' => 'Experiencia, práctica, vida cristianas', 'ss_deweys_id' => '240']);
        DB::table('ts_deweys')->insert(['id' =>'249', 'nombre' => 'Observancias cristianas en la vida familiar', 'ss_deweys_id' => '240']);
        DB::table('ts_deweys')->insert(['id' =>'251', 'nombre' => 'Predicación (Homilética)', 'ss_deweys_id' => '250']);
        DB::table('ts_deweys')->insert(['id' =>'252', 'nombre' => 'Textos de sermones', 'ss_deweys_id' => '250']);
        DB::table('ts_deweys')->insert(['id' =>'253', 'nombre' => 'Oficio pastoral (Teología pastoral)', 'ss_deweys_id' => '250']);
        DB::table('ts_deweys')->insert(['id' =>'254', 'nombre' => 'Gobierno y administración de la parroquia', 'ss_deweys_id' => '250']);
        DB::table('ts_deweys')->insert(['id' =>'255', 'nombre' => 'Congregaciones y órdenes religiosas', 'ss_deweys_id' => '250']);
        DB::table('ts_deweys')->insert(['id' =>'259', 'nombre' => 'Actividades de la iglesia local', 'ss_deweys_id' => '250']);
        DB::table('ts_deweys')->insert(['id' =>'261', 'nombre' => 'Teología social', 'ss_deweys_id' => '260']);
        DB::table('ts_deweys')->insert(['id' =>'262', 'nombre' => 'Eclesiología', 'ss_deweys_id' => '260']);
        DB::table('ts_deweys')->insert(['id' =>'263', 'nombre' => 'Tiempos, lugares de observancia religiosa', 'ss_deweys_id' => '260']);
        DB::table('ts_deweys')->insert(['id' =>'264', 'nombre' => 'Culto público', 'ss_deweys_id' => '260']);
        DB::table('ts_deweys')->insert(['id' =>'265', 'nombre' => 'Sacramentos, otros ritos y actos', 'ss_deweys_id' => '260']);
        DB::table('ts_deweys')->insert(['id' =>'266', 'nombre' => 'Misiones', 'ss_deweys_id' => '260']);
        DB::table('ts_deweys')->insert(['id' =>'267', 'nombre' => 'Asociaciones para trabajo religioso', 'ss_deweys_id' => '260']);
        DB::table('ts_deweys')->insert(['id' =>'268', 'nombre' => 'Educación religiosa', 'ss_deweys_id' => '260']);
        DB::table('ts_deweys')->insert(['id' =>'269', 'nombre' => 'Renovación espiritual', 'ss_deweys_id' => '260']);
        DB::table('ts_deweys')->insert(['id' =>'271', 'nombre' => 'Ordenes religiosas en la historia de la iglesia', 'ss_deweys_id' => '270']);
        DB::table('ts_deweys')->insert(['id' =>'272', 'nombre' => 'Persecuciones en la historia de la iglesia', 'ss_deweys_id' => '270']);
        DB::table('ts_deweys')->insert(['id' =>'273', 'nombre' => 'Herejías en la historia de la iglesia', 'ss_deweys_id' => '270']);
        DB::table('ts_deweys')->insert(['id' =>'274', 'nombre' => 'Iglesia cristiana en Europa', 'ss_deweys_id' => '270']);
        DB::table('ts_deweys')->insert(['id' =>'275', 'nombre' => 'Iglesia cristiana en Asia', 'ss_deweys_id' => '270']);
        DB::table('ts_deweys')->insert(['id' =>'276', 'nombre' => 'Iglesia cristiana en África', 'ss_deweys_id' => '270']);
        DB::table('ts_deweys')->insert(['id' =>'277', 'nombre' => 'Iglesia cristiana en América del Norte', 'ss_deweys_id' => '270']);
        DB::table('ts_deweys')->insert(['id' =>'278', 'nombre' => 'Iglesia cristiana en América del Sur', 'ss_deweys_id' => '270']);
        DB::table('ts_deweys')->insert(['id' =>'279', 'nombre' => 'Iglesia cristiana en otras áreas', 'ss_deweys_id' => '270']);
        DB::table('ts_deweys')->insert(['id' =>'281', 'nombre' => 'Iglesia primitiva y iglesia oriental', 'ss_deweys_id' => '280']);
        DB::table('ts_deweys')->insert(['id' =>'282', 'nombre' => 'Iglesia Católica Romana', 'ss_deweys_id' => '280']);
        DB::table('ts_deweys')->insert(['id' =>'283', 'nombre' => 'Iglesia anglicanas', 'ss_deweys_id' => '280']);
        DB::table('ts_deweys')->insert(['id' =>'284', 'nombre' => 'Protestantes de origen continental', 'ss_deweys_id' => '280']);
        DB::table('ts_deweys')->insert(['id' =>'285', 'nombre' => 'Iglesias Presbiterianas, reformadas, congregacionales', 'ss_deweys_id' => '280']);
        DB::table('ts_deweys')->insert(['id' =>'286', 'nombre' => 'Iglesias bautistas, de los Discípulos de Cristo, adventistas', 'ss_deweys_id' => '280']);
        DB::table('ts_deweys')->insert(['id' =>'287', 'nombre' => 'Iglesia Metodista y relacionadas', 'ss_deweys_id' => '280']);
        DB::table('ts_deweys')->insert(['id' =>'289', 'nombre' => 'Otras denominaciones y sectas', 'ss_deweys_id' => '280']);
        DB::table('ts_deweys')->insert(['id' =>'291', 'nombre' => 'Religión comparada', 'ss_deweys_id' => '290']);
        DB::table('ts_deweys')->insert(['id' =>'292', 'nombre' => 'Religión clásica (griega y romana)', 'ss_deweys_id' => '290']);
        DB::table('ts_deweys')->insert(['id' =>'293', 'nombre' => 'Religión germánica', 'ss_deweys_id' => '290']);
        DB::table('ts_deweys')->insert(['id' =>'294', 'nombre' => 'Religiones de origen hindú', 'ss_deweys_id' => '290']);
        DB::table('ts_deweys')->insert(['id' =>'295', 'nombre' => 'Zoroastrismo (Mazdeismo, Parsismo)', 'ss_deweys_id' => '290']);
        DB::table('ts_deweys')->insert(['id' =>'296', 'nombre' => 'Judaísmo', 'ss_deweys_id' => '290']);
        DB::table('ts_deweys')->insert(['id' =>'297', 'nombre' => 'Islamismo y religiones originadas en él', 'ss_deweys_id' => '290']);
        DB::table('ts_deweys')->insert(['id' =>'299', 'nombre' => 'Otras religiones', 'ss_deweys_id' => '290']);
        DB::table('ts_deweys')->insert(['id' =>'301', 'nombre' => 'Sociología y antropología', 'ss_deweys_id' => '300']);
        DB::table('ts_deweys')->insert(['id' =>'302', 'nombre' => 'Interacción social ', 'ss_deweys_id' => '300']);
        DB::table('ts_deweys')->insert(['id' =>'303', 'nombre' => 'Procesos sociales', 'ss_deweys_id' => '300']);
        DB::table('ts_deweys')->insert(['id' =>'304', 'nombre' => 'Factores que afectan el comportamiento social', 'ss_deweys_id' => '300']);
        DB::table('ts_deweys')->insert(['id' =>'305', 'nombre' => 'Grupos sociales ', 'ss_deweys_id' => '300']);
        DB::table('ts_deweys')->insert(['id' =>'306', 'nombre' => 'Cultura y instituciones', 'ss_deweys_id' => '300']);
        DB::table('ts_deweys')->insert(['id' =>'307', 'nombre' => 'Comunidades', 'ss_deweys_id' => '300']);
        DB::table('ts_deweys')->insert(['id' =>'314', 'nombre' => 'De Europa', 'ss_deweys_id' => '310']);
        DB::table('ts_deweys')->insert(['id' =>'315', 'nombre' => 'De Asia', 'ss_deweys_id' => '310']);
        DB::table('ts_deweys')->insert(['id' =>'316', 'nombre' => 'De África', 'ss_deweys_id' => '310']);
        DB::table('ts_deweys')->insert(['id' =>'317', 'nombre' => 'De América del Norte', 'ss_deweys_id' => '310']);
        DB::table('ts_deweys')->insert(['id' =>'318', 'nombre' => 'De América del Sur', 'ss_deweys_id' => '310']);
        DB::table('ts_deweys')->insert(['id' =>'319', 'nombre' => 'De otras partes del mundo', 'ss_deweys_id' => '310']);
        DB::table('ts_deweys')->insert(['id' =>'321', 'nombre' => 'Sistemas de gobierno y estados', 'ss_deweys_id' => '320']);
        DB::table('ts_deweys')->insert(['id' =>'322', 'nombre' => 'Relaciones del Estado con grupos organizados', 'ss_deweys_id' => '320']);
        DB::table('ts_deweys')->insert(['id' =>'323', 'nombre' => 'Derechos civiles y políticos', 'ss_deweys_id' => '320']);
        DB::table('ts_deweys')->insert(['id' =>'324', 'nombre' => 'El proceso político', 'ss_deweys_id' => '320']);
        DB::table('ts_deweys')->insert(['id' =>'325', 'nombre' => 'Migración y colonización internacionales', 'ss_deweys_id' => '320']);
        DB::table('ts_deweys')->insert(['id' =>'326', 'nombre' => 'Esclavitud y emancipación', 'ss_deweys_id' => '320']);
        DB::table('ts_deweys')->insert(['id' =>'327', 'nombre' => 'Relaciones internacionales', 'ss_deweys_id' => '320']);
        DB::table('ts_deweys')->insert(['id' =>'328', 'nombre' => 'El proceso legislativo', 'ss_deweys_id' => '320']);
        DB::table('ts_deweys')->insert(['id' =>'331', 'nombre' => 'Economía laboral', 'ss_deweys_id' => '330']);
        DB::table('ts_deweys')->insert(['id' =>'332', 'nombre' => 'Economía financiera', 'ss_deweys_id' => '330']);
        DB::table('ts_deweys')->insert(['id' =>'333', 'nombre' => 'Economía de la tierra', 'ss_deweys_id' => '330']);
        DB::table('ts_deweys')->insert(['id' =>'334', 'nombre' => 'Cooperativas', 'ss_deweys_id' => '330']);
        DB::table('ts_deweys')->insert(['id' =>'335', 'nombre' => 'Socialismo y sistemas relacionados', 'ss_deweys_id' => '330']);
        DB::table('ts_deweys')->insert(['id' =>'336', 'nombre' => 'Finanzas públicas', 'ss_deweys_id' => '330']);
        DB::table('ts_deweys')->insert(['id' =>'337', 'nombre' => 'Economía internacional', 'ss_deweys_id' => '330']);
        DB::table('ts_deweys')->insert(['id' =>'338', 'nombre' => 'Producción', 'ss_deweys_id' => '330']);
        DB::table('ts_deweys')->insert(['id' =>'339', 'nombre' => 'Macroeconomía y temas relacionados', 'ss_deweys_id' => '330']);
        DB::table('ts_deweys')->insert(['id' =>'341', 'nombre' => 'Derecho internacional', 'ss_deweys_id' => '340']);
        DB::table('ts_deweys')->insert(['id' =>'342', 'nombre' => 'Derecho constitucional y administrativo', 'ss_deweys_id' => '340']);
        DB::table('ts_deweys')->insert(['id' =>'343', 'nombre' => 'Derecho militar, tributario, mercantil, industrial', 'ss_deweys_id' => '340']);
        DB::table('ts_deweys')->insert(['id' =>'344', 'nombre' => 'Derecho social, laboral, de bienestar social y relacionados', 'ss_deweys_id' => '340']);
        DB::table('ts_deweys')->insert(['id' =>'345', 'nombre' => 'Derecho penal', 'ss_deweys_id' => '340']);
        DB::table('ts_deweys')->insert(['id' =>'346', 'nombre' => 'Derecho privado', 'ss_deweys_id' => '340']);
        DB::table('ts_deweys')->insert(['id' =>'347', 'nombre' => 'Procedimiento y tribunales civiles', 'ss_deweys_id' => '340']);
        DB::table('ts_deweys')->insert(['id' =>'348', 'nombre' => 'Leyes (Estatutos), reglamentaciones, jurisprudencia.', 'ss_deweys_id' => '340']);
        DB::table('ts_deweys')->insert(['id' =>'349', 'nombre' => 'Derecho de jurisprudencia y áreas especificas', 'ss_deweys_id' => '340']);
        DB::table('ts_deweys')->insert(['id' =>'351', 'nombre' => 'De gobiernos centrales', 'ss_deweys_id' => '350']);
        DB::table('ts_deweys')->insert(['id' =>'352', 'nombre' => 'De gobiernos locales', 'ss_deweys_id' => '350']);
        DB::table('ts_deweys')->insert(['id' =>'353', 'nombre' => 'De gobiernos federales y estatales de Estados Unidos', 'ss_deweys_id' => '350']);
        DB::table('ts_deweys')->insert(['id' =>'354', 'nombre' => 'De gobiernos centrales específicos', 'ss_deweys_id' => '350']);
        DB::table('ts_deweys')->insert(['id' =>'355', 'nombre' => 'Ciencia militar', 'ss_deweys_id' => '350']);
        DB::table('ts_deweys')->insert(['id' =>'356', 'nombre' => 'Fuerza y guerra de infantería', 'ss_deweys_id' => '350']);
        DB::table('ts_deweys')->insert(['id' =>'357', 'nombre' => 'Fuerza y guerra montada', 'ss_deweys_id' => '350']);
        DB::table('ts_deweys')->insert(['id' =>'358', 'nombre' => 'Otras fuerzas y servicios especializados', 'ss_deweys_id' => '350']);
        DB::table('ts_deweys')->insert(['id' =>'359', 'nombre' => 'Fuerzas de guerra marítimas (navales)', 'ss_deweys_id' => '350']);
        DB::table('ts_deweys')->insert(['id' =>'361', 'nombre' => 'Problemas sociales y bienestar social en general', 'ss_deweys_id' => '360']);
        DB::table('ts_deweys')->insert(['id' =>'362', 'nombre' => 'Problemas y servicios de bienestar social', 'ss_deweys_id' => '360']);
        DB::table('ts_deweys')->insert(['id' =>'363', 'nombre' => 'Otros problemas y servicios sociales', 'ss_deweys_id' => '360']);
        DB::table('ts_deweys')->insert(['id' =>'364', 'nombre' => 'Criminología', 'ss_deweys_id' => '360']);
        DB::table('ts_deweys')->insert(['id' =>'365', 'nombre' => 'Instituciones penales y relacionadas', 'ss_deweys_id' => '360']);
        DB::table('ts_deweys')->insert(['id' =>'366', 'nombre' => 'Asociaciones', 'ss_deweys_id' => '360']);
        DB::table('ts_deweys')->insert(['id' =>'367', 'nombre' => 'Clubes de carácter general', 'ss_deweys_id' => '360']);
        DB::table('ts_deweys')->insert(['id' =>'368', 'nombre' => 'Seguros', 'ss_deweys_id' => '360']);
        DB::table('ts_deweys')->insert(['id' =>'369', 'nombre' => 'Varias clases de asociaciones', 'ss_deweys_id' => '360']);
        DB::table('ts_deweys')->insert(['id' =>'371', 'nombre' => 'Administración escolar; educación especial', 'ss_deweys_id' => '370']);
        DB::table('ts_deweys')->insert(['id' =>'372', 'nombre' => 'Educación primaria', 'ss_deweys_id' => '370']);
        DB::table('ts_deweys')->insert(['id' =>'373', 'nombre' => 'Educación secundaria', 'ss_deweys_id' => '370']);
        DB::table('ts_deweys')->insert(['id' =>'374', 'nombre' => 'Educación de adultos', 'ss_deweys_id' => '370']);
        DB::table('ts_deweys')->insert(['id' =>'375', 'nombre' => 'Currículos', 'ss_deweys_id' => '370']);
        DB::table('ts_deweys')->insert(['id' =>'376', 'nombre' => 'Educación de las mujeres', 'ss_deweys_id' => '370']);
        DB::table('ts_deweys')->insert(['id' =>'377', 'nombre' => 'Escuelas y religión', 'ss_deweys_id' => '370']);
        DB::table('ts_deweys')->insert(['id' =>'378', 'nombre' => 'Educación superior', 'ss_deweys_id' => '370']);
        DB::table('ts_deweys')->insert(['id' =>'379', 'nombre' => 'Reglamentación, control, apoyo gubernamentales', 'ss_deweys_id' => '370']);
        DB::table('ts_deweys')->insert(['id' =>'381', 'nombre' => 'Comercio interno (Comercio doméstico)', 'ss_deweys_id' => '380']);
        DB::table('ts_deweys')->insert(['id' =>'382', 'nombre' => 'Comercio internacional (Comercio exterior)', 'ss_deweys_id' => '380']);
        DB::table('ts_deweys')->insert(['id' =>'383', 'nombre' => 'Comunicación postal(Correos)', 'ss_deweys_id' => '380']);
        DB::table('ts_deweys')->insert(['id' =>'384', 'nombre' => 'Comunicaciones, Telecomunicaciones', 'ss_deweys_id' => '380']);
        DB::table('ts_deweys')->insert(['id' =>'385', 'nombre' => 'Transporte ferroviario', 'ss_deweys_id' => '380']);
        DB::table('ts_deweys')->insert(['id' =>'386', 'nombre' => 'Transporte por vía acuática interior y en transbordador', 'ss_deweys_id' => '380']);
        DB::table('ts_deweys')->insert(['id' =>'387', 'nombre' => 'Transporte acuático, aéreo, espacial', 'ss_deweys_id' => '380']);
        DB::table('ts_deweys')->insert(['id' =>'388', 'nombre' => 'Transporte, Transporte terrestre', 'ss_deweys_id' => '380']);
        DB::table('ts_deweys')->insert(['id' =>'389', 'nombre' => 'Metrología y normalización', 'ss_deweys_id' => '380']);
        DB::table('ts_deweys')->insert(['id' =>'391', 'nombre' => 'Traje y apariencia personal', 'ss_deweys_id' => '390']);
        DB::table('ts_deweys')->insert(['id' =>'392', 'nombre' => 'Costumbres del ciclo de vida y de la vida doméstica', 'ss_deweys_id' => '390']);
        DB::table('ts_deweys')->insert(['id' =>'393', 'nombre' => 'Costumbres mortuorias', 'ss_deweys_id' => '390']);
        DB::table('ts_deweys')->insert(['id' =>'394', 'nombre' => 'Costumbres generales', 'ss_deweys_id' => '390']);
        DB::table('ts_deweys')->insert(['id' =>'395', 'nombre' => 'Etiqueta (Modales)', 'ss_deweys_id' => '390']);
        DB::table('ts_deweys')->insert(['id' =>'398', 'nombre' => 'Folclor', 'ss_deweys_id' => '390']);
        DB::table('ts_deweys')->insert(['id' =>'399', 'nombre' => 'Costumbres de guerra y diplomacia', 'ss_deweys_id' => '390']);
        DB::table('ts_deweys')->insert(['id' =>'401', 'nombre' => 'Filosofía y teoría', 'ss_deweys_id' => '400']);
        DB::table('ts_deweys')->insert(['id' =>'402', 'nombre' => 'Miscelánea', 'ss_deweys_id' => '400']);
        DB::table('ts_deweys')->insert(['id' =>'403', 'nombre' => 'Diccionarios y enciclopedias', 'ss_deweys_id' => '400']);
        DB::table('ts_deweys')->insert(['id' =>'404', 'nombre' => 'Temas especiales', 'ss_deweys_id' => '400']);
        DB::table('ts_deweys')->insert(['id' =>'405', 'nombre' => 'Publicaciones en serie', 'ss_deweys_id' => '400']);
        DB::table('ts_deweys')->insert(['id' =>'406', 'nombre' => 'Organizaciones y administración', 'ss_deweys_id' => '400']);
        DB::table('ts_deweys')->insert(['id' =>'407', 'nombre' => 'Educación, investigación, temas relacionados', 'ss_deweys_id' => '400']);
        DB::table('ts_deweys')->insert(['id' =>'408', 'nombre' => 'En relación con clases de personas', 'ss_deweys_id' => '400']);
        DB::table('ts_deweys')->insert(['id' =>'409', 'nombre' => 'Tratamiento geográfico y de personas', 'ss_deweys_id' => '400']);
        DB::table('ts_deweys')->insert(['id' =>'411', 'nombre' => 'Sistemas de escritura', 'ss_deweys_id' => '410']);
        DB::table('ts_deweys')->insert(['id' =>'412', 'nombre' => 'Etimología', 'ss_deweys_id' => '410']);
        DB::table('ts_deweys')->insert(['id' =>'413', 'nombre' => 'Diccionarios', 'ss_deweys_id' => '410']);
        DB::table('ts_deweys')->insert(['id' =>'414', 'nombre' => 'Fonología', 'ss_deweys_id' => '410']);
        DB::table('ts_deweys')->insert(['id' =>'415', 'nombre' => 'Sistemas estructurales (Gramática)', 'ss_deweys_id' => '410']);
        DB::table('ts_deweys')->insert(['id' =>'417', 'nombre' => 'Dialectología y lingüística histórica', 'ss_deweys_id' => '410']);
        DB::table('ts_deweys')->insert(['id' =>'418', 'nombre' => 'Uso estándar, Lingüística aplicada', 'ss_deweys_id' => '410']);
        DB::table('ts_deweys')->insert(['id' =>'419', 'nombre' => 'Lenguajes verbales no hablados ni escritos', 'ss_deweys_id' => '410']);
        DB::table('ts_deweys')->insert(['id' =>'421', 'nombre' => 'Sistema de escritura y fonología inglesa', 'ss_deweys_id' => '420']);
        DB::table('ts_deweys')->insert(['id' =>'422', 'nombre' => 'Etimología inglesa', 'ss_deweys_id' => '420']);
        DB::table('ts_deweys')->insert(['id' =>'423', 'nombre' => 'Diccionarios de inglés', 'ss_deweys_id' => '420']);
        DB::table('ts_deweys')->insert(['id' =>'425', 'nombre' => 'Gramática inglesa', 'ss_deweys_id' => '420']);
        DB::table('ts_deweys')->insert(['id' =>'427', 'nombre' => 'Variaciones de le lengua inglesa', 'ss_deweys_id' => '420']);
        DB::table('ts_deweys')->insert(['id' =>'428', 'nombre' => 'Uso del inglés estándar', 'ss_deweys_id' => '420']);
        DB::table('ts_deweys')->insert(['id' =>'429', 'nombre' => 'Ingles antiguo (Anglosajón)', 'ss_deweys_id' => '420']);
        DB::table('ts_deweys')->insert(['id' =>'431', 'nombre' => 'Sistemas de escritura y fonología alemana', 'ss_deweys_id' => '430']);
        DB::table('ts_deweys')->insert(['id' =>'432', 'nombre' => 'Etimología alemana', 'ss_deweys_id' => '430']);
        DB::table('ts_deweys')->insert(['id' =>'433', 'nombre' => 'Diccionario de Alemán', 'ss_deweys_id' => '430']);
        DB::table('ts_deweys')->insert(['id' =>'435', 'nombre' => 'Gramática alemana', 'ss_deweys_id' => '430']);
        DB::table('ts_deweys')->insert(['id' =>'437', 'nombre' => 'Variaciones de la lengua alemana', 'ss_deweys_id' => '430']);
        DB::table('ts_deweys')->insert(['id' =>'438', 'nombre' => 'Uso del alemán estándar', 'ss_deweys_id' => '430']);
        DB::table('ts_deweys')->insert(['id' =>'439', 'nombre' => 'Otras lenguas germánicas', 'ss_deweys_id' => '430']);
        DB::table('ts_deweys')->insert(['id' =>'441', 'nombre' => 'Sistema de escritura y fonología franceses', 'ss_deweys_id' => '440']);
        DB::table('ts_deweys')->insert(['id' =>'442', 'nombre' => 'Etimología francesa', 'ss_deweys_id' => '440']);
        DB::table('ts_deweys')->insert(['id' =>'443', 'nombre' => 'Diccionario de francés', 'ss_deweys_id' => '440']);
        DB::table('ts_deweys')->insert(['id' =>'445', 'nombre' => 'Gramática francesa', 'ss_deweys_id' => '440']);
        DB::table('ts_deweys')->insert(['id' =>'447', 'nombre' => 'Variaciones del francés', 'ss_deweys_id' => '440']);
        DB::table('ts_deweys')->insert(['id' =>'448', 'nombre' => 'Uso del francés estándar', 'ss_deweys_id' => '440']);
        DB::table('ts_deweys')->insert(['id' =>'449', 'nombre' => 'Provenzal y catalán', 'ss_deweys_id' => '440']);
        DB::table('ts_deweys')->insert(['id' =>'451', 'nombre' => 'Sistema de escritura y fonología italianos', 'ss_deweys_id' => '450']);
        DB::table('ts_deweys')->insert(['id' =>'452', 'nombre' => 'Etimología italiana', 'ss_deweys_id' => '450']);
        DB::table('ts_deweys')->insert(['id' =>'453', 'nombre' => 'Diccionarios de italiano', 'ss_deweys_id' => '450']);
        DB::table('ts_deweys')->insert(['id' =>'455', 'nombre' => 'Gramática italiana', 'ss_deweys_id' => '450']);
        DB::table('ts_deweys')->insert(['id' =>'457', 'nombre' => 'Variaciones del italiano', 'ss_deweys_id' => '450']);
        DB::table('ts_deweys')->insert(['id' =>'458', 'nombre' => 'Uso del italiano estándar', 'ss_deweys_id' => '450']);
        DB::table('ts_deweys')->insert(['id' =>'459', 'nombre' => 'Rumano y retorromano', 'ss_deweys_id' => '450']);
        DB::table('ts_deweys')->insert(['id' =>'461', 'nombre' => 'Sistema de escritura y fonología', 'ss_deweys_id' => '460']);
        DB::table('ts_deweys')->insert(['id' =>'462', 'nombre' => 'Etimología española', 'ss_deweys_id' => '460']);
        DB::table('ts_deweys')->insert(['id' =>'463', 'nombre' => 'Diccionarios de español', 'ss_deweys_id' => '460']);
        DB::table('ts_deweys')->insert(['id' =>'465', 'nombre' => 'Gramática española', 'ss_deweys_id' => '460']);
        DB::table('ts_deweys')->insert(['id' =>'467', 'nombre' => 'Variaciones del español', 'ss_deweys_id' => '460']);
        DB::table('ts_deweys')->insert(['id' =>'468', 'nombre' => 'Uso del español estándar', 'ss_deweys_id' => '460']);
        DB::table('ts_deweys')->insert(['id' =>'469', 'nombre' => 'Portugués', 'ss_deweys_id' => '460']);
        DB::table('ts_deweys')->insert(['id' =>'471', 'nombre' => 'Escritura y fonología latinas clásicas', 'ss_deweys_id' => '470']);
        DB::table('ts_deweys')->insert(['id' =>'472', 'nombre' => 'Etimología latina clásica', 'ss_deweys_id' => '470']);
        DB::table('ts_deweys')->insert(['id' =>'473', 'nombre' => 'Diccionarios de latín clásico', 'ss_deweys_id' => '470']);
        DB::table('ts_deweys')->insert(['id' =>'475', 'nombre' => 'Gramática latina clásica', 'ss_deweys_id' => '470']);
        DB::table('ts_deweys')->insert(['id' =>'477', 'nombre' => 'Latín arcaico, postclásico, vulgar', 'ss_deweys_id' => '470']);
        DB::table('ts_deweys')->insert(['id' =>'478', 'nombre' => 'Uso del latín clásico', 'ss_deweys_id' => '470']);
        DB::table('ts_deweys')->insert(['id' =>'479', 'nombre' => 'Otras lenguas itálicas', 'ss_deweys_id' => '470']);
        DB::table('ts_deweys')->insert(['id' =>'481', 'nombre' => 'Escritura y fonología griegas clásicas', 'ss_deweys_id' => '480']);
        DB::table('ts_deweys')->insert(['id' =>'482', 'nombre' => 'Etimología griega clásica', 'ss_deweys_id' => '480']);
        DB::table('ts_deweys')->insert(['id' =>'483', 'nombre' => 'Diccionarios de griego clásico', 'ss_deweys_id' => '480']);
        DB::table('ts_deweys')->insert(['id' =>'485', 'nombre' => 'Gramática griega clásica', 'ss_deweys_id' => '480']);
        DB::table('ts_deweys')->insert(['id' =>'487', 'nombre' => 'Griego preclásico y postclasico', 'ss_deweys_id' => '480']);
        DB::table('ts_deweys')->insert(['id' =>'488', 'nombre' => 'Uso del griego clásico', 'ss_deweys_id' => '480']);
        DB::table('ts_deweys')->insert(['id' =>'489', 'nombre' => 'Otras lenguas helénicas', 'ss_deweys_id' => '480']);
        DB::table('ts_deweys')->insert(['id' =>'491', 'nombre' => 'Lenguas indoeuropeas orientales y celtas', 'ss_deweys_id' => '490']);
        DB::table('ts_deweys')->insert(['id' =>'492', 'nombre' => 'Lenguas afroasiáticas, Semíticas', 'ss_deweys_id' => '490']);
        DB::table('ts_deweys')->insert(['id' =>'493', 'nombre' => 'Lenguas afroasiáticas, no semíticas', 'ss_deweys_id' => '490']);
        DB::table('ts_deweys')->insert(['id' =>'494', 'nombre' => 'Lenguas uralaltaicas, paleosiberianas, dravidas', 'ss_deweys_id' => '490']);
        DB::table('ts_deweys')->insert(['id' =>'495', 'nombre' => 'Lenguas del oriente y sudoriente de Asia', 'ss_deweys_id' => '490']);
        DB::table('ts_deweys')->insert(['id' =>'496', 'nombre' => 'Lenguas africanas', 'ss_deweys_id' => '490']);
        DB::table('ts_deweys')->insert(['id' =>'497', 'nombre' => 'Lenguas nativas de América del Norte', 'ss_deweys_id' => '490']);
        DB::table('ts_deweys')->insert(['id' =>'498', 'nombre' => 'Lenguas nativas de América del Sur', 'ss_deweys_id' => '490']);
        DB::table('ts_deweys')->insert(['id' =>'499', 'nombre' => 'Lenguas varias', 'ss_deweys_id' => '490']);
        DB::table('ts_deweys')->insert(['id' =>'501', 'nombre' => 'Filosofía y teoría ', 'ss_deweys_id' => '500']);
        DB::table('ts_deweys')->insert(['id' =>'502', 'nombre' => 'Miscelánea', 'ss_deweys_id' => '500']);
        DB::table('ts_deweys')->insert(['id' =>'503', 'nombre' => 'Diccionarios y enciclopedias', 'ss_deweys_id' => '500']);
        DB::table('ts_deweys')->insert(['id' =>'505', 'nombre' => 'Probabilidades en serie', 'ss_deweys_id' => '500']);
        DB::table('ts_deweys')->insert(['id' =>'506', 'nombre' => 'Probabilidades y administración', 'ss_deweys_id' => '500']);
        DB::table('ts_deweys')->insert(['id' =>'507', 'nombre' => 'Probabilidades, temas relacionados', 'ss_deweys_id' => '500']);
        DB::table('ts_deweys')->insert(['id' =>'508', 'nombre' => 'Historia natural', 'ss_deweys_id' => '500']);
        DB::table('ts_deweys')->insert(['id' =>'509', 'nombre' => 'Tratamiento histórico, geográfico, de personas', 'ss_deweys_id' => '500']);
        DB::table('ts_deweys')->insert(['id' =>'511', 'nombre' => 'Principios generales', 'ss_deweys_id' => '510']);
        DB::table('ts_deweys')->insert(['id' =>'512', 'nombre' => 'Álgebra y teoría de los números', 'ss_deweys_id' => '510']);
        DB::table('ts_deweys')->insert(['id' =>'513', 'nombre' => 'Aritmética', 'ss_deweys_id' => '510']);
        DB::table('ts_deweys')->insert(['id' =>'514', 'nombre' => 'Topología', 'ss_deweys_id' => '510']);
        DB::table('ts_deweys')->insert(['id' =>'515', 'nombre' => 'Análisis', 'ss_deweys_id' => '510']);
        DB::table('ts_deweys')->insert(['id' =>'516', 'nombre' => 'Geometría', 'ss_deweys_id' => '510']);
        DB::table('ts_deweys')->insert(['id' =>'519', 'nombre' => 'Probabilidades y matemáticas aplicadas', 'ss_deweys_id' => '510']);
        DB::table('ts_deweys')->insert(['id' =>'521', 'nombre' => 'Mecánica celeste', 'ss_deweys_id' => '520']);
        DB::table('ts_deweys')->insert(['id' =>'522', 'nombre' => 'Técnicas, equipo, materiales', 'ss_deweys_id' => '520']);
        DB::table('ts_deweys')->insert(['id' =>'523', 'nombre' => 'Cuerpos y fenómenos celestes específicos', 'ss_deweys_id' => '520']);
        DB::table('ts_deweys')->insert(['id' =>'525', 'nombre' => 'La Tierra (Geografía astronómica)', 'ss_deweys_id' => '520']);
        DB::table('ts_deweys')->insert(['id' =>'526', 'nombre' => 'Geografía matemática', 'ss_deweys_id' => '520']);
        DB::table('ts_deweys')->insert(['id' =>'527', 'nombre' => 'Probabilidad celeste', 'ss_deweys_id' => '520']);
        DB::table('ts_deweys')->insert(['id' =>'528', 'nombre' => 'Efemérides', 'ss_deweys_id' => '520']);
        DB::table('ts_deweys')->insert(['id' =>'529', 'nombre' => 'Cronología', 'ss_deweys_id' => '520']);
        DB::table('ts_deweys')->insert(['id' =>'531', 'nombre' => 'Mecánica clásica, Mecánica de sólidos', 'ss_deweys_id' => '530']);
        DB::table('ts_deweys')->insert(['id' =>'532', 'nombre' => 'Mecánica de fluidos, Mecánica de líquidos', 'ss_deweys_id' => '530']);
        DB::table('ts_deweys')->insert(['id' =>'533', 'nombre' => 'Mecánicas de gases', 'ss_deweys_id' => '530']);
        DB::table('ts_deweys')->insert(['id' =>'534', 'nombre' => 'Sonido y vibraciones relacionadas', 'ss_deweys_id' => '530']);
        DB::table('ts_deweys')->insert(['id' =>'535', 'nombre' => 'Luz y fenómenos parafóticos', 'ss_deweys_id' => '530']);
        DB::table('ts_deweys')->insert(['id' =>'536', 'nombre' => 'Calor', 'ss_deweys_id' => '530']);
        DB::table('ts_deweys')->insert(['id' =>'537', 'nombre' => 'Electricidad y electrónica', 'ss_deweys_id' => '530']);
        DB::table('ts_deweys')->insert(['id' =>'538', 'nombre' => 'Magnetismo', 'ss_deweys_id' => '530']);
        DB::table('ts_deweys')->insert(['id' =>'539', 'nombre' => 'Física moderna', 'ss_deweys_id' => '530']);
        DB::table('ts_deweys')->insert(['id' =>'541', 'nombre' => 'Química física y teórica', 'ss_deweys_id' => '540']);
        DB::table('ts_deweys')->insert(['id' =>'542', 'nombre' => 'Técnicas, equipo, materiales', 'ss_deweys_id' => '540']);
        DB::table('ts_deweys')->insert(['id' =>'543', 'nombre' => 'Química analítica', 'ss_deweys_id' => '540']);
        DB::table('ts_deweys')->insert(['id' =>'544', 'nombre' => 'Análisis cualitativo', 'ss_deweys_id' => '540']);
        DB::table('ts_deweys')->insert(['id' =>'545', 'nombre' => 'Análisis cuantitativo', 'ss_deweys_id' => '540']);
        DB::table('ts_deweys')->insert(['id' =>'546', 'nombre' => 'Química inorgánica', 'ss_deweys_id' => '540']);
        DB::table('ts_deweys')->insert(['id' =>'547', 'nombre' => 'Química orgánica', 'ss_deweys_id' => '540']);
        DB::table('ts_deweys')->insert(['id' =>'548', 'nombre' => 'Cristalografía', 'ss_deweys_id' => '540']);
        DB::table('ts_deweys')->insert(['id' =>'549', 'nombre' => 'Mineralogía', 'ss_deweys_id' => '540']);
        DB::table('ts_deweys')->insert(['id' =>'551', 'nombre' => 'Geología, hidrología, meteorología', 'ss_deweys_id' => '550']);
        DB::table('ts_deweys')->insert(['id' =>'552', 'nombre' => 'Petrología', 'ss_deweys_id' => '550']);
        DB::table('ts_deweys')->insert(['id' =>'553', 'nombre' => 'Geología económica', 'ss_deweys_id' => '550']);
        DB::table('ts_deweys')->insert(['id' =>'554', 'nombre' => 'Ciencias de la tierra de Europa', 'ss_deweys_id' => '550']);
        DB::table('ts_deweys')->insert(['id' =>'555', 'nombre' => 'De Asia', 'ss_deweys_id' => '550']);
        DB::table('ts_deweys')->insert(['id' =>'556', 'nombre' => 'De África', 'ss_deweys_id' => '550']);
        DB::table('ts_deweys')->insert(['id' =>'557', 'nombre' => 'De América del Norte', 'ss_deweys_id' => '550']);
        DB::table('ts_deweys')->insert(['id' =>'558', 'nombre' => 'De América del Sur', 'ss_deweys_id' => '550']);
        DB::table('ts_deweys')->insert(['id' =>'559', 'nombre' => 'De otras áreas', 'ss_deweys_id' => '550']);
        DB::table('ts_deweys')->insert(['id' =>'561', 'nombre' => 'Paleobotánica', 'ss_deweys_id' => '560']);
        DB::table('ts_deweys')->insert(['id' =>'562', 'nombre' => 'Invertebrados fósiles', 'ss_deweys_id' => '560']);
        DB::table('ts_deweys')->insert(['id' =>'563', 'nombre' => 'Filos (phyla) y fósiles primitivos', 'ss_deweys_id' => '560']);
        DB::table('ts_deweys')->insert(['id' =>'564', 'nombre' => 'Moluscos y Moluscoideos fósiles', 'ss_deweys_id' => '560']);
        DB::table('ts_deweys')->insert(['id' =>'565', 'nombre' => 'Otros invertebrados fósiles', 'ss_deweys_id' => '560']);
        DB::table('ts_deweys')->insert(['id' =>'566', 'nombre' => 'Vertebrados fósiles (Craniatos fósiles)', 'ss_deweys_id' => '560']);
        DB::table('ts_deweys')->insert(['id' =>'567', 'nombre' => 'Vertebrados de sangre fría fósiles', 'ss_deweys_id' => '560']);
        DB::table('ts_deweys')->insert(['id' =>'568', 'nombre' => 'Aves fósiles (Pájaros fósiles)', 'ss_deweys_id' => '560']);
        DB::table('ts_deweys')->insert(['id' =>'569', 'nombre' => 'Mamíferos fósiles', 'ss_deweys_id' => '560']);
        DB::table('ts_deweys')->insert(['id' =>'572', 'nombre' => 'Razas humanas', 'ss_deweys_id' => '570']);
        DB::table('ts_deweys')->insert(['id' =>'573', 'nombre' => 'Antropología física', 'ss_deweys_id' => '570']);
        DB::table('ts_deweys')->insert(['id' =>'574', 'nombre' => 'Biología', 'ss_deweys_id' => '570']);
        DB::table('ts_deweys')->insert(['id' =>'575', 'nombre' => 'Evolución y genética', 'ss_deweys_id' => '570']);
        DB::table('ts_deweys')->insert(['id' =>'576', 'nombre' => 'Microbiología', 'ss_deweys_id' => '570']);
        DB::table('ts_deweys')->insert(['id' =>'577', 'nombre' => 'Naturaleza general de la vida', 'ss_deweys_id' => '570']);
        DB::table('ts_deweys')->insert(['id' =>'578', 'nombre' => 'Microscopia en biología', 'ss_deweys_id' => '570']);
        DB::table('ts_deweys')->insert(['id' =>'579', 'nombre' => 'Colección y preservación', 'ss_deweys_id' => '570']);
        DB::table('ts_deweys')->insert(['id' =>'581', 'nombre' => 'Botánica', 'ss_deweys_id' => '580']);
        DB::table('ts_deweys')->insert(['id' =>'582', 'nombre' => 'Espermatofitas (plantas con semilla)', 'ss_deweys_id' => '580']);
        DB::table('ts_deweys')->insert(['id' =>'583', 'nombre' => 'Dicotiledóneas', 'ss_deweys_id' => '580']);
        DB::table('ts_deweys')->insert(['id' =>'584', 'nombre' => 'Monocotiledóneas', 'ss_deweys_id' => '580']);
        DB::table('ts_deweys')->insert(['id' =>'585', 'nombre' => 'Gimnospermas (Pinofitas)', 'ss_deweys_id' => '580']);
        DB::table('ts_deweys')->insert(['id' =>'586', 'nombre' => 'Criptógamas (Plantas sin semilla)', 'ss_deweys_id' => '580']);
        DB::table('ts_deweys')->insert(['id' =>'587', 'nombre' => 'Pteridofitas (Criptógamas vasculares)', 'ss_deweys_id' => '580']);
        DB::table('ts_deweys')->insert(['id' =>'588', 'nombre' => 'Briofitas', 'ss_deweys_id' => '580']);
        DB::table('ts_deweys')->insert(['id' =>'589', 'nombre' => 'Talabiontas y procariotas', 'ss_deweys_id' => '580']);
        DB::table('ts_deweys')->insert(['id' =>'591', 'nombre' => 'Zoología', 'ss_deweys_id' => '590']);
        DB::table('ts_deweys')->insert(['id' =>'592', 'nombre' => 'Invertebrados', 'ss_deweys_id' => '590']);
        DB::table('ts_deweys')->insert(['id' =>'593', 'nombre' => 'Protozoos, Equinodermos, filos (phyla) relacionados', 'ss_deweys_id' => '590']);
        DB::table('ts_deweys')->insert(['id' =>'594', 'nombre' => 'Moluscos y moluscoideos', 'ss_deweys_id' => '590']);
        DB::table('ts_deweys')->insert(['id' =>'595', 'nombre' => 'Otros invertebrados', 'ss_deweys_id' => '590']);
        DB::table('ts_deweys')->insert(['id' =>'596', 'nombre' => 'Vertebrados (Craneados, vertebrados)', 'ss_deweys_id' => '590']);
        DB::table('ts_deweys')->insert(['id' =>'597', 'nombre' => 'Vertebrados de sangre fría, Peces', 'ss_deweys_id' => '590']);
        DB::table('ts_deweys')->insert(['id' =>'598', 'nombre' => 'Aves (Pájaros)', 'ss_deweys_id' => '590']);
        DB::table('ts_deweys')->insert(['id' =>'599', 'nombre' => 'Mamíferos', 'ss_deweys_id' => '590']);
        DB::table('ts_deweys')->insert(['id' =>'601', 'nombre' => 'Filosofía y teoría', 'ss_deweys_id' => '600']);
        DB::table('ts_deweys')->insert(['id' =>'602', 'nombre' => 'Miscelánea', 'ss_deweys_id' => '600']);
        DB::table('ts_deweys')->insert(['id' =>'603', 'nombre' => 'Diccionarios y enciclopedias', 'ss_deweys_id' => '600']);
        DB::table('ts_deweys')->insert(['id' =>'604', 'nombre' => 'Temas especiales', 'ss_deweys_id' => '600']);
        DB::table('ts_deweys')->insert(['id' =>'605', 'nombre' => 'Publicaciones en serie', 'ss_deweys_id' => '600']);
        DB::table('ts_deweys')->insert(['id' =>'606', 'nombre' => 'Organizaciones', 'ss_deweys_id' => '600']);
        DB::table('ts_deweys')->insert(['id' =>'607', 'nombre' => 'Educación, investigación, temas relacionados', 'ss_deweys_id' => '600']);
        DB::table('ts_deweys')->insert(['id' =>'608', 'nombre' => 'Inventos y patentes', 'ss_deweys_id' => '600']);
        DB::table('ts_deweys')->insert(['id' =>'609', 'nombre' => 'Tratamiento histórico, geográfico, de personas', 'ss_deweys_id' => '600']);
        DB::table('ts_deweys')->insert(['id' =>'611', 'nombre' => 'Anatomía humana, citología, histología', 'ss_deweys_id' => '610']);
        DB::table('ts_deweys')->insert(['id' =>'612', 'nombre' => 'Fisiología humana', 'ss_deweys_id' => '610']);
        DB::table('ts_deweys')->insert(['id' =>'613', 'nombre' => 'Promoción de salud', 'ss_deweys_id' => '610']);
        DB::table('ts_deweys')->insert(['id' =>'614', 'nombre' => 'Incidencia y prevención de la enfermedad', 'ss_deweys_id' => '610']);
        DB::table('ts_deweys')->insert(['id' =>'615', 'nombre' => 'Farmacología y terapéutica', 'ss_deweys_id' => '610']);
        DB::table('ts_deweys')->insert(['id' =>'616', 'nombre' => 'Enfermedades', 'ss_deweys_id' => '610']);
        DB::table('ts_deweys')->insert(['id' =>'617', 'nombre' => 'Varias ramas de la medicina, Cirugía', 'ss_deweys_id' => '610']);
        DB::table('ts_deweys')->insert(['id' =>'618', 'nombre' => 'Ginecología y otras especialidades médicas', 'ss_deweys_id' => '610']);
        DB::table('ts_deweys')->insert(['id' =>'619', 'nombre' => 'Medicina experimental', 'ss_deweys_id' => '610']);
        DB::table('ts_deweys')->insert(['id' =>'621', 'nombre' => 'Física aplicada', 'ss_deweys_id' => '620']);
        DB::table('ts_deweys')->insert(['id' =>'622', 'nombre' => 'Minería y operaciones relacionadas', 'ss_deweys_id' => '620']);
        DB::table('ts_deweys')->insert(['id' =>'623', 'nombre' => 'Ingeniería militar y naval', 'ss_deweys_id' => '620']);
        DB::table('ts_deweys')->insert(['id' =>'624', 'nombre' => 'Ingeniería civil', 'ss_deweys_id' => '620']);
        DB::table('ts_deweys')->insert(['id' =>'625', 'nombre' => 'Ingeniería de ferrocarriles, de caminos', 'ss_deweys_id' => '620']);
        DB::table('ts_deweys')->insert(['id' =>'627', 'nombre' => 'Ingeniería hidráulica', 'ss_deweys_id' => '620']);
        DB::table('ts_deweys')->insert(['id' =>'628', 'nombre' => 'Ingeniería sanitaria y municipal', 'ss_deweys_id' => '620']);
        DB::table('ts_deweys')->insert(['id' =>'629', 'nombre' => 'Otras ramas de la ingeniería', 'ss_deweys_id' => '620']);
        DB::table('ts_deweys')->insert(['id' =>'631', 'nombre' => 'Técnicas, equipo, materiales', 'ss_deweys_id' => '630']);
        DB::table('ts_deweys')->insert(['id' =>'632', 'nombre' => 'Lesiones, enfermedades, plagas de las plantas', 'ss_deweys_id' => '630']);
        DB::table('ts_deweys')->insert(['id' =>'633', 'nombre' => 'Cultivos de campo y plantaciones', 'ss_deweys_id' => '630']);
        DB::table('ts_deweys')->insert(['id' =>'634', 'nombre' => 'Huertos, frutas, silvicultura', 'ss_deweys_id' => '630']);
        DB::table('ts_deweys')->insert(['id' =>'635', 'nombre' => 'Cultivos horticolas (Horticultura)', 'ss_deweys_id' => '630']);
        DB::table('ts_deweys')->insert(['id' =>'636', 'nombre' => 'Producción animal (Zootecnia)', 'ss_deweys_id' => '630']);
        DB::table('ts_deweys')->insert(['id' =>'637', 'nombre' => 'Procedimiento lechero y productos relacionados', 'ss_deweys_id' => '630']);
        DB::table('ts_deweys')->insert(['id' =>'638', 'nombre' => 'Cultivo de insectos', 'ss_deweys_id' => '630']);
        DB::table('ts_deweys')->insert(['id' =>'639', 'nombre' => 'Caza, pesca, conservación', 'ss_deweys_id' => '630']);
        DB::table('ts_deweys')->insert(['id' =>'641', 'nombre' => 'Alimentos y bebidas', 'ss_deweys_id' => '640']);
        DB::table('ts_deweys')->insert(['id' =>'642', 'nombre' => 'Comidas y servicio a la mesa', 'ss_deweys_id' => '640']);
        DB::table('ts_deweys')->insert(['id' =>'643', 'nombre' => 'Vivienda y equipo de la casa', 'ss_deweys_id' => '640']);
        DB::table('ts_deweys')->insert(['id' =>'644', 'nombre' => 'Servicios de la casa', 'ss_deweys_id' => '640']);
        DB::table('ts_deweys')->insert(['id' =>'645', 'nombre' => 'Dotación de la casa', 'ss_deweys_id' => '640']);
        DB::table('ts_deweys')->insert(['id' =>'646', 'nombre' => 'Costura, vestuario, vida personal', 'ss_deweys_id' => '640']);
        DB::table('ts_deweys')->insert(['id' =>'647', 'nombre' => 'Administración de viviendas públicas', 'ss_deweys_id' => '640']);
        DB::table('ts_deweys')->insert(['id' =>'648', 'nombre' => 'Manejo de la casa', 'ss_deweys_id' => '640']);
        DB::table('ts_deweys')->insert(['id' =>'649', 'nombre' => 'Puericultura y atención domiciliaria del enfermo', 'ss_deweys_id' => '640']);
        DB::table('ts_deweys')->insert(['id' =>'651', 'nombre' => 'Servicios de oficina', 'ss_deweys_id' => '650']);
        DB::table('ts_deweys')->insert(['id' =>'652', 'nombre' => 'Procesos de comunicación escrita', 'ss_deweys_id' => '650']);
        DB::table('ts_deweys')->insert(['id' =>'653', 'nombre' => 'Taquigrafía', 'ss_deweys_id' => '650']);
        DB::table('ts_deweys')->insert(['id' =>'657', 'nombre' => 'Contabilidad', 'ss_deweys_id' => '650']);
        DB::table('ts_deweys')->insert(['id' =>'658', 'nombre' => 'Administración general', 'ss_deweys_id' => '650']);
        DB::table('ts_deweys')->insert(['id' =>'659', 'nombre' => 'Publicidad y relaciones públicas', 'ss_deweys_id' => '650']);
        DB::table('ts_deweys')->insert(['id' =>'661', 'nombre' => 'Tecnología química industria', 'ss_deweys_id' => '660']);
        DB::table('ts_deweys')->insert(['id' =>'662', 'nombre' => 'Tecnología de explosivos y combustibles', 'ss_deweys_id' => '660']);
        DB::table('ts_deweys')->insert(['id' =>'663', 'nombre' => 'Tecnología de las bebidas', 'ss_deweys_id' => '660']);
        DB::table('ts_deweys')->insert(['id' =>'664', 'nombre' => 'Tecnología de los alimentos', 'ss_deweys_id' => '660']);
        DB::table('ts_deweys')->insert(['id' =>'665', 'nombre' => 'Aceites industriales, grasas, ceras, gases', 'ss_deweys_id' => '660']);
        DB::table('ts_deweys')->insert(['id' =>'666', 'nombre' => 'Cerámica y tecnologías afines', 'ss_deweys_id' => '660']);
        DB::table('ts_deweys')->insert(['id' =>'667', 'nombre' => 'Limpieza, color, tecnologías relacionadas', 'ss_deweys_id' => '660']);
        DB::table('ts_deweys')->insert(['id' =>'668', 'nombre' => 'Tecnología de otros productos orgánicos', 'ss_deweys_id' => '660']);
        DB::table('ts_deweys')->insert(['id' =>'669', 'nombre' => 'Metalurgia', 'ss_deweys_id' => '660']);
        DB::table('ts_deweys')->insert(['id' =>'671', 'nombre' => 'Metalistería y productos metálicos', 'ss_deweys_id' => '670']);
        DB::table('ts_deweys')->insert(['id' =>'672', 'nombre' => 'Hierro, acero, otras aleaciones ferrosas', 'ss_deweys_id' => '670']);
        DB::table('ts_deweys')->insert(['id' =>'673', 'nombre' => 'Metales no ferrosos', 'ss_deweys_id' => '670']);
        DB::table('ts_deweys')->insert(['id' =>'674', 'nombre' => 'Procesamiento de madera aserrada, productos de madera, corcho', 'ss_deweys_id' => '670']);
        DB::table('ts_deweys')->insert(['id' =>'675', 'nombre' => 'Procesamiento del cuero y piel', 'ss_deweys_id' => '670']);
        DB::table('ts_deweys')->insert(['id' =>'676', 'nombre' => 'Tecnología de la pulpa y del papel', 'ss_deweys_id' => '670']);
        DB::table('ts_deweys')->insert(['id' =>'677', 'nombre' => 'Textiles', 'ss_deweys_id' => '670']);
        DB::table('ts_deweys')->insert(['id' =>'678', 'nombre' => 'Elastómeros y productos del elastómero', 'ss_deweys_id' => '670']);
        DB::table('ts_deweys')->insert(['id' =>'679', 'nombre' => 'Otros productos de materiales específicos', 'ss_deweys_id' => '670']);
        DB::table('ts_deweys')->insert(['id' =>'681', 'nombre' => 'Instrumentos de precisión y otros dispositivos', 'ss_deweys_id' => '680']);
        DB::table('ts_deweys')->insert(['id' =>'682', 'nombre' => 'Trabajo de forja pequeña (Herrería)', 'ss_deweys_id' => '680']);
        DB::table('ts_deweys')->insert(['id' =>'683', 'nombre' => 'Ferretería y aparatos de la casa', 'ss_deweys_id' => '680']);
        DB::table('ts_deweys')->insert(['id' =>'684', 'nombre' => 'Muebles y talleres de hogar', 'ss_deweys_id' => '680']);
        DB::table('ts_deweys')->insert(['id' =>'685', 'nombre' => 'Productos de cuero, piel, relacionados ', 'ss_deweys_id' => '680']);
        DB::table('ts_deweys')->insert(['id' =>'686', 'nombre' => 'Imprentas y actividades relacionadas', 'ss_deweys_id' => '680']);
        DB::table('ts_deweys')->insert(['id' =>'687', 'nombre' => 'Vestuario', 'ss_deweys_id' => '680']);
        DB::table('ts_deweys')->insert(['id' =>'688', 'nombre' => 'Otros productos acabados, empaques', 'ss_deweys_id' => '680']);
        DB::table('ts_deweys')->insert(['id' =>'691', 'nombre' => 'Materiales de construcción', 'ss_deweys_id' => '690']);
        DB::table('ts_deweys')->insert(['id' =>'692', 'nombre' => 'Prácticas auxiliares de la construcción', 'ss_deweys_id' => '690']);
        DB::table('ts_deweys')->insert(['id' =>'693', 'nombre' => 'Materiales y propósitos específicos', 'ss_deweys_id' => '690']);
        DB::table('ts_deweys')->insert(['id' =>'694', 'nombre' => 'Construcción en madera, Carpintería', 'ss_deweys_id' => '690']);
        DB::table('ts_deweys')->insert(['id' =>'695', 'nombre' => 'Cubiertas (techos)', 'ss_deweys_id' => '690']);
        DB::table('ts_deweys')->insert(['id' =>'696', 'nombre' => 'Servicios públicos', 'ss_deweys_id' => '690']);
        DB::table('ts_deweys')->insert(['id' =>'697', 'nombre' => 'Calefacción, ventilación, aire acondicionado', 'ss_deweys_id' => '690']);
        DB::table('ts_deweys')->insert(['id' =>'698', 'nombre' => 'Detalles de acabado', 'ss_deweys_id' => '690']);
        DB::table('ts_deweys')->insert(['id' =>'701', 'nombre' => 'Filosofía y teoría', 'ss_deweys_id' => '700']);
        DB::table('ts_deweys')->insert(['id' =>'702', 'nombre' => 'Miscelánea', 'ss_deweys_id' => '700']);
        DB::table('ts_deweys')->insert(['id' =>'703', 'nombre' => 'Diccionarios y enciclopedias', 'ss_deweys_id' => '700']);
        DB::table('ts_deweys')->insert(['id' =>'704', 'nombre' => 'Temas especiales', 'ss_deweys_id' => '700']);
        DB::table('ts_deweys')->insert(['id' =>'705', 'nombre' => 'Publicaciones en serie', 'ss_deweys_id' => '700']);
        DB::table('ts_deweys')->insert(['id' =>'706', 'nombre' => 'Organizaciones y administración', 'ss_deweys_id' => '700']);
        DB::table('ts_deweys')->insert(['id' =>'707', 'nombre' => 'Educación, investigación, temas relacionados', 'ss_deweys_id' => '700']);
        DB::table('ts_deweys')->insert(['id' =>'708', 'nombre' => 'Galerías, museos, colecciones privadas', 'ss_deweys_id' => '700']);
        DB::table('ts_deweys')->insert(['id' =>'709', 'nombre' => 'Tratamiento histórico, geográfico, personas', 'ss_deweys_id' => '700']);
        DB::table('ts_deweys')->insert(['id' =>'711', 'nombre' => 'Planificación del espacio (Urbanismo)', 'ss_deweys_id' => '710']);
        DB::table('ts_deweys')->insert(['id' =>'712', 'nombre' => 'Arquitectura del paisaje', 'ss_deweys_id' => '710']);
        DB::table('ts_deweys')->insert(['id' =>'713', 'nombre' => 'Arquitectura del paisaje de las vías de tránsito', 'ss_deweys_id' => '710']);
        DB::table('ts_deweys')->insert(['id' =>'714', 'nombre' => 'Aguas ornamentales', 'ss_deweys_id' => '710']);
        DB::table('ts_deweys')->insert(['id' =>'715', 'nombre' => 'Plantas leñosas', 'ss_deweys_id' => '710']);
        DB::table('ts_deweys')->insert(['id' =>'716', 'nombre' => 'Plantas herbáceas', 'ss_deweys_id' => '710']);
        DB::table('ts_deweys')->insert(['id' =>'717', 'nombre' => 'Estructuras', 'ss_deweys_id' => '710']);
        DB::table('ts_deweys')->insert(['id' =>'718', 'nombre' => 'Diseño de paisaje de cementerios', 'ss_deweys_id' => '710']);
        DB::table('ts_deweys')->insert(['id' =>'719', 'nombre' => 'Paisajes naturales', 'ss_deweys_id' => '710']);
        DB::table('ts_deweys')->insert(['id' =>'721', 'nombre' => 'Estructura arquitectónica', 'ss_deweys_id' => '720']);
        DB::table('ts_deweys')->insert(['id' =>'722', 'nombre' => 'Arquitectura antigua hasta ca. 300', 'ss_deweys_id' => '720']);
        DB::table('ts_deweys')->insert(['id' =>'723', 'nombre' => 'Arquitectura desde ca. 300 hasta 1399', 'ss_deweys_id' => '720']);
        DB::table('ts_deweys')->insert(['id' =>'724', 'nombre' => 'Arquitectura desde 1400', 'ss_deweys_id' => '720']);
        DB::table('ts_deweys')->insert(['id' =>'725', 'nombre' => 'Estructuras públicas', 'ss_deweys_id' => '720']);
        DB::table('ts_deweys')->insert(['id' =>'726', 'nombre' => 'Edificios para propósitos religiosos', 'ss_deweys_id' => '720']);
        DB::table('ts_deweys')->insert(['id' =>'727', 'nombre' => 'Edificios para educación y investigación', 'ss_deweys_id' => '720']);
        DB::table('ts_deweys')->insert(['id' =>'728', 'nombre' => 'Edificios residenciales y relacionados', 'ss_deweys_id' => '720']);
        DB::table('ts_deweys')->insert(['id' =>'729', 'nombre' => 'Diseño y decoración', 'ss_deweys_id' => '720']);
        DB::table('ts_deweys')->insert(['id' =>'731', 'nombre' => 'Procesos, formas, temas de la escultura', 'ss_deweys_id' => '730']);
        DB::table('ts_deweys')->insert(['id' =>'732', 'nombre' => 'La escultura hasta ca. 500', 'ss_deweys_id' => '730']);
        DB::table('ts_deweys')->insert(['id' =>'733', 'nombre' => 'Escultura griega, etrusca, romana', 'ss_deweys_id' => '730']);
        DB::table('ts_deweys')->insert(['id' =>'734', 'nombre' => 'Escultura desde ca. 500 hasta 1399', 'ss_deweys_id' => '730']);
        DB::table('ts_deweys')->insert(['id' =>'735', 'nombre' => 'Escultura desde 1400', 'ss_deweys_id' => '730']);
        DB::table('ts_deweys')->insert(['id' =>'736', 'nombre' => 'Talla y tallado', 'ss_deweys_id' => '730']);
        DB::table('ts_deweys')->insert(['id' =>'737', 'nombre' => 'Numismátismo y sigilografía', 'ss_deweys_id' => '730']);
        DB::table('ts_deweys')->insert(['id' =>'738', 'nombre' => 'Artes cerámicas', 'ss_deweys_id' => '730']);
        DB::table('ts_deweys')->insert(['id' =>'739', 'nombre' => 'Arte en metal', 'ss_deweys_id' => '730']);
        DB::table('ts_deweys')->insert(['id' =>'741', 'nombre' => 'Dibujo y dibujos', 'ss_deweys_id' => '740']);
        DB::table('ts_deweys')->insert(['id' =>'742', 'nombre' => 'Perspectiva', 'ss_deweys_id' => '740']);
        DB::table('ts_deweys')->insert(['id' =>'743', 'nombre' => 'Dibujo y dibujos por tema', 'ss_deweys_id' => '740']);
        DB::table('ts_deweys')->insert(['id' =>'745', 'nombre' => 'Artes decorativas', 'ss_deweys_id' => '740']);
        DB::table('ts_deweys')->insert(['id' =>'746', 'nombre' => 'Artes textiles', 'ss_deweys_id' => '740']);
        DB::table('ts_deweys')->insert(['id' =>'747', 'nombre' => 'Decoración de interiores', 'ss_deweys_id' => '740']);
        DB::table('ts_deweys')->insert(['id' =>'748', 'nombre' => 'Vidrio', 'ss_deweys_id' => '740']);
        DB::table('ts_deweys')->insert(['id' =>'749', 'nombre' => 'Muebles y accesorios', 'ss_deweys_id' => '740']);
        DB::table('ts_deweys')->insert(['id' =>'751', 'nombre' => 'Técnicas, equipo, formas', 'ss_deweys_id' => '750']);
        DB::table('ts_deweys')->insert(['id' =>'752', 'nombre' => 'Color', 'ss_deweys_id' => '750']);
        DB::table('ts_deweys')->insert(['id' =>'753', 'nombre' => 'Simbolismo, alegoría, mitología, leyenda', 'ss_deweys_id' => '750']);
        DB::table('ts_deweys')->insert(['id' =>'754', 'nombre' => 'Pinturas de género', 'ss_deweys_id' => '750']);
        DB::table('ts_deweys')->insert(['id' =>'755', 'nombre' => 'Religión y simbolismo religiosos', 'ss_deweys_id' => '750']);
        DB::table('ts_deweys')->insert(['id' =>'757', 'nombre' => 'Figuras humanas y sus partes', 'ss_deweys_id' => '750']);
        DB::table('ts_deweys')->insert(['id' =>'758', 'nombre' => 'Otros temas', 'ss_deweys_id' => '750']);
        DB::table('ts_deweys')->insert(['id' =>'759', 'nombre' => 'Tratamiento histórico, geográfico, de personas', 'ss_deweys_id' => '750']);
        DB::table('ts_deweys')->insert(['id' =>'761', 'nombre' => 'Procesos en relieve (Grabado en bloque)', 'ss_deweys_id' => '760']);
        DB::table('ts_deweys')->insert(['id' =>'763', 'nombre' => 'Procesos litográficos (Planográficos)', 'ss_deweys_id' => '760']);
        DB::table('ts_deweys')->insert(['id' =>'764', 'nombre' => 'Cromolitografia y serigrafía', 'ss_deweys_id' => '760']);
        DB::table('ts_deweys')->insert(['id' =>'765', 'nombre' => 'Grabado en meta', 'ss_deweys_id' => '760']);
        DB::table('ts_deweys')->insert(['id' =>'766', 'nombre' => 'Media tinta y procesos relacionados', 'ss_deweys_id' => '760']);
        DB::table('ts_deweys')->insert(['id' =>'767', 'nombre' => 'Aguafuerte y grabado a buril', 'ss_deweys_id' => '760']);
        DB::table('ts_deweys')->insert(['id' =>'769', 'nombre' => 'Grabados', 'ss_deweys_id' => '760']);
        DB::table('ts_deweys')->insert(['id' =>'771', 'nombre' => 'Técnicas, equipo, materiales', 'ss_deweys_id' => '770']);
        DB::table('ts_deweys')->insert(['id' =>'772', 'nombre' => 'Procesos con sales metálicas', 'ss_deweys_id' => '770']);
        DB::table('ts_deweys')->insert(['id' =>'773', 'nombre' => 'Procesos de pigmentación de la impresión', 'ss_deweys_id' => '770']);
        DB::table('ts_deweys')->insert(['id' =>'774', 'nombre' => 'Holografía', 'ss_deweys_id' => '770']);
        DB::table('ts_deweys')->insert(['id' =>'778', 'nombre' => 'Campos y clases de fotografía', 'ss_deweys_id' => '770']);
        DB::table('ts_deweys')->insert(['id' =>'779', 'nombre' => 'Fotografía', 'ss_deweys_id' => '770']);
        DB::table('ts_deweys')->insert(['id' =>'781', 'nombre' => 'Principios generales y formas musicales', 'ss_deweys_id' => '780']);
        DB::table('ts_deweys')->insert(['id' =>'782', 'nombre' => 'Música vocal', 'ss_deweys_id' => '780']);
        DB::table('ts_deweys')->insert(['id' =>'783', 'nombre' => 'Música para voces individuales, la voz', 'ss_deweys_id' => '780']);
        DB::table('ts_deweys')->insert(['id' =>'784', 'nombre' => 'Instrumentos y conjuntos instrumentales', 'ss_deweys_id' => '780']);
        DB::table('ts_deweys')->insert(['id' =>'785', 'nombre' => 'Conjuntos con un solo instrumento por parte', 'ss_deweys_id' => '780']);
        DB::table('ts_deweys')->insert(['id' =>'786', 'nombre' => 'Instrumentos de percusión y otros instrumentos', 'ss_deweys_id' => '780']);
        DB::table('ts_deweys')->insert(['id' =>'787', 'nombre' => 'Instrumentos de cuerda (Cordófonos)', 'ss_deweys_id' => '780']);
        DB::table('ts_deweys')->insert(['id' =>'788', 'nombre' => 'Instrumentos de viento (Aerófonos)', 'ss_deweys_id' => '780']);
        DB::table('ts_deweys')->insert(['id' =>'791', 'nombre' => 'Representaciones públicas', 'ss_deweys_id' => '790']);
        DB::table('ts_deweys')->insert(['id' =>'792', 'nombre' => 'Representaciones escénicas', 'ss_deweys_id' => '790']);
        DB::table('ts_deweys')->insert(['id' =>'793', 'nombre' => 'Juegos y pasatiempos bajo techo', 'ss_deweys_id' => '790']);
        DB::table('ts_deweys')->insert(['id' =>'794', 'nombre' => 'Juegos de destreza bajo techo', 'ss_deweys_id' => '790']);
        DB::table('ts_deweys')->insert(['id' =>'795', 'nombre' => 'Juegos de suerte', 'ss_deweys_id' => '790']);
        DB::table('ts_deweys')->insert(['id' =>'796', 'nombre' => 'Deportes y juegos atléticos y al aire libre', 'ss_deweys_id' => '790']);
        DB::table('ts_deweys')->insert(['id' =>'797', 'nombre' => 'Deportes acuáticos y aéreos', 'ss_deweys_id' => '790']);
        DB::table('ts_deweys')->insert(['id' =>'798', 'nombre' => 'Deportes ecuestres', 'ss_deweys_id' => '790']);
        DB::table('ts_deweys')->insert(['id' =>'799', 'nombre' => 'Pesca, caza, tiro', 'ss_deweys_id' => '790']);
        DB::table('ts_deweys')->insert(['id' =>'801', 'nombre' => 'Filosofía y retórica', 'ss_deweys_id' => '800']);
        DB::table('ts_deweys')->insert(['id' =>'802', 'nombre' => 'Miscelánea', 'ss_deweys_id' => '800']);
        DB::table('ts_deweys')->insert(['id' =>'803', 'nombre' => 'Diccionarios y enciclopedias', 'ss_deweys_id' => '800']);
        DB::table('ts_deweys')->insert(['id' =>'805', 'nombre' => 'Publicaciones en serie', 'ss_deweys_id' => '800']);
        DB::table('ts_deweys')->insert(['id' =>'806', 'nombre' => 'Organizaciones', 'ss_deweys_id' => '800']);
        DB::table('ts_deweys')->insert(['id' =>'807', 'nombre' => 'Educación, investigación, temas relacionados', 'ss_deweys_id' => '800']);
        DB::table('ts_deweys')->insert(['id' =>'808', 'nombre' => 'Retórica y colecciones de literatura', 'ss_deweys_id' => '800']);
        DB::table('ts_deweys')->insert(['id' =>'809', 'nombre' => 'Historia y critica literaria', 'ss_deweys_id' => '800']);
        DB::table('ts_deweys')->insert(['id' =>'811', 'nombre' => 'Poesía', 'ss_deweys_id' => '810']);
        DB::table('ts_deweys')->insert(['id' =>'812', 'nombre' => 'Teatro', 'ss_deweys_id' => '810']);
        DB::table('ts_deweys')->insert(['id' =>'813', 'nombre' => 'Novelista', 'ss_deweys_id' => '810']);
        DB::table('ts_deweys')->insert(['id' =>'814', 'nombre' => 'Ensayo', 'ss_deweys_id' => '810']);
        DB::table('ts_deweys')->insert(['id' =>'815', 'nombre' => 'Oratoria', 'ss_deweys_id' => '810']);
        DB::table('ts_deweys')->insert(['id' =>'816', 'nombre' => 'Cartas', 'ss_deweys_id' => '810']);
        DB::table('ts_deweys')->insert(['id' =>'817', 'nombre' => 'Sátira y humor', 'ss_deweys_id' => '810']);
        DB::table('ts_deweys')->insert(['id' =>'818', 'nombre' => 'Escritos varios', 'ss_deweys_id' => '810']);
        DB::table('ts_deweys')->insert(['id' =>'821', 'nombre' => 'Poesía inglesa', 'ss_deweys_id' => '820']);
        DB::table('ts_deweys')->insert(['id' =>'822', 'nombre' => 'Teatro ingles', 'ss_deweys_id' => '820']);
        DB::table('ts_deweys')->insert(['id' =>'823', 'nombre' => 'Novelística', 'ss_deweys_id' => '820']);
        DB::table('ts_deweys')->insert(['id' =>'824', 'nombre' => 'Ensayos', 'ss_deweys_id' => '820']);
        DB::table('ts_deweys')->insert(['id' =>'825', 'nombre' => 'Oratoria', 'ss_deweys_id' => '820']);
        DB::table('ts_deweys')->insert(['id' =>'826', 'nombre' => 'Cartas', 'ss_deweys_id' => '820']);
        DB::table('ts_deweys')->insert(['id' =>'827', 'nombre' => 'Sátira y humor', 'ss_deweys_id' => '820']);
        DB::table('ts_deweys')->insert(['id' =>'828', 'nombre' => 'Escritos varios', 'ss_deweys_id' => '820']);
        DB::table('ts_deweys')->insert(['id' =>'829', 'nombre' => 'Literatura inglesa antigua (anglosajona)', 'ss_deweys_id' => '820']);
        DB::table('ts_deweys')->insert(['id' =>'831', 'nombre' => 'Poesía', 'ss_deweys_id' => '830']);
        DB::table('ts_deweys')->insert(['id' =>'832', 'nombre' => 'Teatro', 'ss_deweys_id' => '830']);
        DB::table('ts_deweys')->insert(['id' =>'833', 'nombre' => 'Ficción', 'ss_deweys_id' => '830']);
        DB::table('ts_deweys')->insert(['id' =>'834', 'nombre' => 'Ensayos', 'ss_deweys_id' => '830']);
        DB::table('ts_deweys')->insert(['id' =>'835', 'nombre' => 'Oratoria', 'ss_deweys_id' => '830']);
        DB::table('ts_deweys')->insert(['id' =>'836', 'nombre' => 'Cartas', 'ss_deweys_id' => '830']);
        DB::table('ts_deweys')->insert(['id' =>'837', 'nombre' => 'Sátira y humor', 'ss_deweys_id' => '830']);
        DB::table('ts_deweys')->insert(['id' =>'838', 'nombre' => 'Escritos varios', 'ss_deweys_id' => '830']);
        DB::table('ts_deweys')->insert(['id' =>'839', 'nombre' => 'Otras literaturas germánicas', 'ss_deweys_id' => '830']);
        DB::table('ts_deweys')->insert(['id' =>'841', 'nombre' => 'Poesía francesa', 'ss_deweys_id' => '840']);
        DB::table('ts_deweys')->insert(['id' =>'842', 'nombre' => 'Teatro francés', 'ss_deweys_id' => '840']);
        DB::table('ts_deweys')->insert(['id' =>'843', 'nombre' => 'Novela francesa', 'ss_deweys_id' => '840']);
        DB::table('ts_deweys')->insert(['id' =>'844', 'nombre' => 'Ensayos franceses', 'ss_deweys_id' => '840']);
        DB::table('ts_deweys')->insert(['id' =>'845', 'nombre' => 'Oratoria francesa', 'ss_deweys_id' => '840']);
        DB::table('ts_deweys')->insert(['id' =>'846', 'nombre' => 'Cartas francesas', 'ss_deweys_id' => '840']);
        DB::table('ts_deweys')->insert(['id' =>'847', 'nombre' => 'Sátira y humor francés', 'ss_deweys_id' => '840']);
        DB::table('ts_deweys')->insert(['id' =>'848', 'nombre' => 'Escritos varios franceses', 'ss_deweys_id' => '840']);
        DB::table('ts_deweys')->insert(['id' =>'849', 'nombre' => 'Provenzal y catalán', 'ss_deweys_id' => '840']);
        DB::table('ts_deweys')->insert(['id' =>'851', 'nombre' => 'Poesía italiana', 'ss_deweys_id' => '850']);
        DB::table('ts_deweys')->insert(['id' =>'852', 'nombre' => 'Teatro italiano', 'ss_deweys_id' => '850']);
        DB::table('ts_deweys')->insert(['id' =>'853', 'nombre' => 'Ficción italiana', 'ss_deweys_id' => '850']);
        DB::table('ts_deweys')->insert(['id' =>'854', 'nombre' => 'Ensayos italianos', 'ss_deweys_id' => '850']);
        DB::table('ts_deweys')->insert(['id' =>'855', 'nombre' => 'Oratoria italiana', 'ss_deweys_id' => '850']);
        DB::table('ts_deweys')->insert(['id' =>'856', 'nombre' => 'Cartas italianas', 'ss_deweys_id' => '850']);
        DB::table('ts_deweys')->insert(['id' =>'857', 'nombre' => 'Sátiras y humor italiano', 'ss_deweys_id' => '850']);
        DB::table('ts_deweys')->insert(['id' =>'858', 'nombre' => 'Escritos varios italianos', 'ss_deweys_id' => '850']);
        DB::table('ts_deweys')->insert(['id' =>'859', 'nombre' => 'Romano y retorromano', 'ss_deweys_id' => '850']);
        DB::table('ts_deweys')->insert(['id' =>'861', 'nombre' => 'Poesía española', 'ss_deweys_id' => '860']);
        DB::table('ts_deweys')->insert(['id' =>'862', 'nombre' => 'Teatro español', 'ss_deweys_id' => '860']);
        DB::table('ts_deweys')->insert(['id' =>'863', 'nombre' => 'Ficción española', 'ss_deweys_id' => '860']);
        DB::table('ts_deweys')->insert(['id' =>'864', 'nombre' => 'Ensayos españoles', 'ss_deweys_id' => '860']);
        DB::table('ts_deweys')->insert(['id' =>'865', 'nombre' => 'Oratoria española', 'ss_deweys_id' => '860']);
        DB::table('ts_deweys')->insert(['id' =>'866', 'nombre' => 'Cartas españolas', 'ss_deweys_id' => '860']);
        DB::table('ts_deweys')->insert(['id' =>'867', 'nombre' => 'Sátira y humor españoles', 'ss_deweys_id' => '860']);
        DB::table('ts_deweys')->insert(['id' =>'868', 'nombre' => 'Escritos varios españoles', 'ss_deweys_id' => '860']);
        DB::table('ts_deweys')->insert(['id' =>'869', 'nombre' => 'Literatura portuguesa', 'ss_deweys_id' => '860']);
        DB::table('ts_deweys')->insert(['id' =>'871', 'nombre' => 'Poesía latina', 'ss_deweys_id' => '870']);
        DB::table('ts_deweys')->insert(['id' =>'872', 'nombre' => 'Poesía dramática y teatro latinos', 'ss_deweys_id' => '870']);
        DB::table('ts_deweys')->insert(['id' =>'873', 'nombre' => 'Poesía épica y novelística latinas', 'ss_deweys_id' => '870']);
        DB::table('ts_deweys')->insert(['id' =>'874', 'nombre' => 'Poesía lírica latina', 'ss_deweys_id' => '870']);
        DB::table('ts_deweys')->insert(['id' =>'875', 'nombre' => 'Oratoria latina', 'ss_deweys_id' => '870']);
        DB::table('ts_deweys')->insert(['id' =>'876', 'nombre' => 'Cartas latinas', 'ss_deweys_id' => '870']);
        DB::table('ts_deweys')->insert(['id' =>'877', 'nombre' => 'Sátira y humor latinos', 'ss_deweys_id' => '870']);
        DB::table('ts_deweys')->insert(['id' =>'878', 'nombre' => 'Escritos varios latinos', 'ss_deweys_id' => '870']);
        DB::table('ts_deweys')->insert(['id' =>'879', 'nombre' => 'Literaturas de otras lenguas itálicas', 'ss_deweys_id' => '870']);
        DB::table('ts_deweys')->insert(['id' =>'881', 'nombre' => 'Poesía griega clásica', 'ss_deweys_id' => '880']);
        DB::table('ts_deweys')->insert(['id' =>'882', 'nombre' => 'Teatro griego clásico', 'ss_deweys_id' => '880']);
        DB::table('ts_deweys')->insert(['id' =>'883', 'nombre' => 'Poesía épica y novelística griega clásica', 'ss_deweys_id' => '880']);
        DB::table('ts_deweys')->insert(['id' =>'884', 'nombre' => 'Poesía lírica griega clásica', 'ss_deweys_id' => '880']);
        DB::table('ts_deweys')->insert(['id' =>'885', 'nombre' => 'Oratoria griega clásica', 'ss_deweys_id' => '880']);
        DB::table('ts_deweys')->insert(['id' =>'886', 'nombre' => 'Cartas griegas clásicas', 'ss_deweys_id' => '880']);
        DB::table('ts_deweys')->insert(['id' =>'887', 'nombre' => 'Sátira y humor griegos clásicos', 'ss_deweys_id' => '880']);
        DB::table('ts_deweys')->insert(['id' =>'888', 'nombre' => 'Escritos varios griegos clásicos', 'ss_deweys_id' => '880']);
        DB::table('ts_deweys')->insert(['id' =>'889', 'nombre' => 'Literatura griega moderna', 'ss_deweys_id' => '880']);
        DB::table('ts_deweys')->insert(['id' =>'891', 'nombre' => 'Indoeuropeas, orientales y célticas', 'ss_deweys_id' => '890']);
        DB::table('ts_deweys')->insert(['id' =>'892', 'nombre' => 'Afroasiáticas, Semíticas', 'ss_deweys_id' => '890']);
        DB::table('ts_deweys')->insert(['id' =>'893', 'nombre' => 'Afroasiáticas no semíticas', 'ss_deweys_id' => '890']);
        DB::table('ts_deweys')->insert(['id' =>'894', 'nombre' => 'Uralaltaicas, paleosiberianas y darvinianas', 'ss_deweys_id' => '890']);
        DB::table('ts_deweys')->insert(['id' =>'895', 'nombre' => 'Del oriente y Sudoriente de Asia', 'ss_deweys_id' => '890']);
        DB::table('ts_deweys')->insert(['id' =>'897', 'nombre' => 'Nativas de América del Norte', 'ss_deweys_id' => '890']);
        DB::table('ts_deweys')->insert(['id' =>'898', 'nombre' => 'Nativas de América del Sur', 'ss_deweys_id' => '890']);
        DB::table('ts_deweys')->insert(['id' =>'899', 'nombre' => 'Otras lenguas', 'ss_deweys_id' => '890']);
        DB::table('ts_deweys')->insert(['id' =>'901', 'nombre' => 'Filosofía y teoría de la historia', 'ss_deweys_id' => '900']);
        DB::table('ts_deweys')->insert(['id' =>'902', 'nombre' => 'Miscelánea', 'ss_deweys_id' => '900']);
        DB::table('ts_deweys')->insert(['id' =>'903', 'nombre' => 'Diccionarios y enciclopedias', 'ss_deweys_id' => '900']);
        DB::table('ts_deweys')->insert(['id' =>'904', 'nombre' => 'Colecciones de relatos de eventos', 'ss_deweys_id' => '900']);
        DB::table('ts_deweys')->insert(['id' =>'905', 'nombre' => 'Publicaciones en serie', 'ss_deweys_id' => '900']);
        DB::table('ts_deweys')->insert(['id' =>'906', 'nombre' => 'Organizaciones y administración', 'ss_deweys_id' => '900']);
        DB::table('ts_deweys')->insert(['id' =>'907', 'nombre' => 'Educación, investigación, temas relacionados', 'ss_deweys_id' => '900']);
        DB::table('ts_deweys')->insert(['id' =>'908', 'nombre' => 'En relación con clases de personas', 'ss_deweys_id' => '900']);
        DB::table('ts_deweys')->insert(['id' =>'909', 'nombre' => 'Historia universal', 'ss_deweys_id' => '900']);
        DB::table('ts_deweys')->insert(['id' =>'911', 'nombre' => 'Geografía histórica', 'ss_deweys_id' => '910']);
        DB::table('ts_deweys')->insert(['id' =>'912', 'nombre' => 'Representaciones gráficas de la tierra', 'ss_deweys_id' => '910']);
        DB::table('ts_deweys')->insert(['id' =>'913', 'nombre' => 'Mundo antiguo', 'ss_deweys_id' => '910']);
        DB::table('ts_deweys')->insert(['id' =>'914', 'nombre' => 'Europa', 'ss_deweys_id' => '910']);
        DB::table('ts_deweys')->insert(['id' =>'915', 'nombre' => 'Asia', 'ss_deweys_id' => '910']);
        DB::table('ts_deweys')->insert(['id' =>'916', 'nombre' => 'África', 'ss_deweys_id' => '910']);
        DB::table('ts_deweys')->insert(['id' =>'917', 'nombre' => 'América del Norte', 'ss_deweys_id' => '910']);
        DB::table('ts_deweys')->insert(['id' =>'918', 'nombre' => 'América del Sur', 'ss_deweys_id' => '910']);
        DB::table('ts_deweys')->insert(['id' =>'919', 'nombre' => 'Otras áreas', 'ss_deweys_id' => '910']);
        DB::table('ts_deweys')->insert(['id' =>'929', 'nombre' => 'Genealogía, nombres, emblemas', 'ss_deweys_id' => '920']);
        DB::table('ts_deweys')->insert(['id' =>'931', 'nombre' => 'China', 'ss_deweys_id' => '930']);
        DB::table('ts_deweys')->insert(['id' =>'932', 'nombre' => 'Egipto', 'ss_deweys_id' => '930']);
        DB::table('ts_deweys')->insert(['id' =>'933', 'nombre' => 'Palestina', 'ss_deweys_id' => '930']);
        DB::table('ts_deweys')->insert(['id' =>'934', 'nombre' => 'India', 'ss_deweys_id' => '930']);
        DB::table('ts_deweys')->insert(['id' =>'935', 'nombre' => 'Mesopotamia y Meseta Iraní', 'ss_deweys_id' => '930']);
        DB::table('ts_deweys')->insert(['id' =>'936', 'nombre' => 'Europa al norte y al occidente de Italia', 'ss_deweys_id' => '930']);
        DB::table('ts_deweys')->insert(['id' =>'937', 'nombre' => 'Italia y territorios adyacentes', 'ss_deweys_id' => '930']);
        DB::table('ts_deweys')->insert(['id' =>'938', 'nombre' => 'Grecia', 'ss_deweys_id' => '930']);
        DB::table('ts_deweys')->insert(['id' =>'939', 'nombre' => 'Otras partes del mundo antiguo', 'ss_deweys_id' => '930']);
        DB::table('ts_deweys')->insert(['id' =>'941', 'nombre' => 'Islas Británicas', 'ss_deweys_id' => '940']);
        DB::table('ts_deweys')->insert(['id' =>'942', 'nombre' => 'Inglaterra y Gales', 'ss_deweys_id' => '940']);
        DB::table('ts_deweys')->insert(['id' =>'943', 'nombre' => 'Europa Central, Alemania', 'ss_deweys_id' => '940']);
        DB::table('ts_deweys')->insert(['id' =>'944', 'nombre' => 'Francia y Mónaco', 'ss_deweys_id' => '940']);
        DB::table('ts_deweys')->insert(['id' =>'945', 'nombre' => 'Península Itálica e islas adyacentes', 'ss_deweys_id' => '940']);
        DB::table('ts_deweys')->insert(['id' =>'946', 'nombre' => 'Península Ibérica e islas adyacentes', 'ss_deweys_id' => '940']);
        DB::table('ts_deweys')->insert(['id' =>'947', 'nombre' => 'Europa Oriental, Rusia ', 'ss_deweys_id' => '940']);
        DB::table('ts_deweys')->insert(['id' =>'948', 'nombre' => 'Europa del norte, Escandinavia', 'ss_deweys_id' => '940']);
        DB::table('ts_deweys')->insert(['id' =>'949', 'nombre' => 'Otras partes de Europa', 'ss_deweys_id' => '940']);
        DB::table('ts_deweys')->insert(['id' =>'951', 'nombre' => 'China y áreas adyacentes', 'ss_deweys_id' => '950']);
        DB::table('ts_deweys')->insert(['id' =>'952', 'nombre' => 'Japón', 'ss_deweys_id' => '950']);
        DB::table('ts_deweys')->insert(['id' =>'953', 'nombre' => 'Península de Arabia y áreas adyacentes', 'ss_deweys_id' => '950']);
        DB::table('ts_deweys')->insert(['id' =>'954', 'nombre' => 'Asia de Sur, India', 'ss_deweys_id' => '950']);
        DB::table('ts_deweys')->insert(['id' =>'955', 'nombre' => 'Irán', 'ss_deweys_id' => '950']);
        DB::table('ts_deweys')->insert(['id' =>'956', 'nombre' => 'Medio Oriente (Cercano Oriente)', 'ss_deweys_id' => '950']);
        DB::table('ts_deweys')->insert(['id' =>'957', 'nombre' => 'Siberia (Rusia asiática)', 'ss_deweys_id' => '950']);
        DB::table('ts_deweys')->insert(['id' =>'958', 'nombre' => 'Asia central', 'ss_deweys_id' => '950']);
        DB::table('ts_deweys')->insert(['id' =>'959', 'nombre' => 'Asia sudoriental', 'ss_deweys_id' => '950']);
        DB::table('ts_deweys')->insert(['id' =>'961', 'nombre' => 'Túnez y Libia', 'ss_deweys_id' => '960']);
        DB::table('ts_deweys')->insert(['id' =>'962', 'nombre' => 'Egipto y Sudán', 'ss_deweys_id' => '960']);
        DB::table('ts_deweys')->insert(['id' =>'963', 'nombre' => 'Etiopía', 'ss_deweys_id' => '960']);
        DB::table('ts_deweys')->insert(['id' =>'964', 'nombre' => 'Marruecos e Islas Canarias', 'ss_deweys_id' => '960']);
        DB::table('ts_deweys')->insert(['id' =>'965', 'nombre' => 'Argelia', 'ss_deweys_id' => '960']);
        DB::table('ts_deweys')->insert(['id' =>'966', 'nombre' => 'África occidental e islas cercanas', 'ss_deweys_id' => '960']);
        DB::table('ts_deweys')->insert(['id' =>'967', 'nombre' => 'África central e islas cercanas', 'ss_deweys_id' => '960']);
        DB::table('ts_deweys')->insert(['id' =>'968', 'nombre' => 'África del Sur', 'ss_deweys_id' => '960']);
        DB::table('ts_deweys')->insert(['id' =>'969', 'nombre' => 'Islas del Océano Indico del Sur', 'ss_deweys_id' => '960']);
        DB::table('ts_deweys')->insert(['id' =>'971', 'nombre' => 'Canadá', 'ss_deweys_id' => '970']);
        DB::table('ts_deweys')->insert(['id' =>'972', 'nombre' => 'Mesoamérica, México ', 'ss_deweys_id' => '970']);
        DB::table('ts_deweys')->insert(['id' =>'973', 'nombre' => 'Estados Unidos', 'ss_deweys_id' => '970']);
        DB::table('ts_deweys')->insert(['id' =>'974', 'nombre' => 'Noroccidente de Estados Unidos', 'ss_deweys_id' => '970']);
        DB::table('ts_deweys')->insert(['id' =>'975', 'nombre' => 'Sudoriente de Estados Unidos', 'ss_deweys_id' => '970']);
        DB::table('ts_deweys')->insert(['id' =>'976', 'nombre' => 'Centro-sur de Estados Unidos', 'ss_deweys_id' => '970']);
        DB::table('ts_deweys')->insert(['id' =>'977', 'nombre' => 'Centro-norte de Estados Unidos', 'ss_deweys_id' => '970']);
        DB::table('ts_deweys')->insert(['id' =>'978', 'nombre' => 'Occidente de Estados Unidos', 'ss_deweys_id' => '970']);
        DB::table('ts_deweys')->insert(['id' =>'979', 'nombre' => 'Gran Cuenca y Vertiente del Pacífico', 'ss_deweys_id' => '970']);
        DB::table('ts_deweys')->insert(['id' =>'981', 'nombre' => 'Brasil', 'ss_deweys_id' => '980']);
        DB::table('ts_deweys')->insert(['id' =>'982', 'nombre' => 'Argentina', 'ss_deweys_id' => '980']);
        DB::table('ts_deweys')->insert(['id' =>'983', 'nombre' => 'Chile', 'ss_deweys_id' => '980']);
        DB::table('ts_deweys')->insert(['id' =>'984', 'nombre' => 'Bolivia', 'ss_deweys_id' => '980']);
        DB::table('ts_deweys')->insert(['id' =>'985', 'nombre' => 'Perú', 'ss_deweys_id' => '980']);
        DB::table('ts_deweys')->insert(['id' =>'986', 'nombre' => 'Colombia y Ecuador', 'ss_deweys_id' => '980']);
        DB::table('ts_deweys')->insert(['id' =>'987', 'nombre' => 'Venezuela', 'ss_deweys_id' => '980']);
        DB::table('ts_deweys')->insert(['id' =>'988', 'nombre' => 'Guayanas', 'ss_deweys_id' => '980']);
        DB::table('ts_deweys')->insert(['id' =>'989', 'nombre' => 'Paraguay y Uruguay', 'ss_deweys_id' => '980']);
        DB::table('ts_deweys')->insert(['id' =>'993', 'nombre' => 'Nueva Zelanda', 'ss_deweys_id' => '990']);
        DB::table('ts_deweys')->insert(['id' =>'994', 'nombre' => 'Australia', 'ss_deweys_id' => '990']);
        DB::table('ts_deweys')->insert(['id' =>'995', 'nombre' => 'Melanesia, Nueva Guinea', 'ss_deweys_id' => '990']);
        DB::table('ts_deweys')->insert(['id' =>'996', 'nombre' => 'Otras partes del Pacífico, Polinesia', 'ss_deweys_id' => '990']);
        DB::table('ts_deweys')->insert(['id' =>'997', 'nombre' => 'Islas del Océano Atlántico', 'ss_deweys_id' => '990']);
        DB::table('ts_deweys')->insert(['id' =>'998', 'nombre' => 'Islas árticas y Antártida', 'ss_deweys_id' => '990']);
        DB::table('ts_deweys')->insert(['id' =>'999', 'nombre' => 'Mundos extraterrestres', 'ss_deweys_id' => '990']);
    }
}
